<?php

declare(strict_types=1);

$cards = require __DIR__.'/envy-cards.php';
$section = static fn ($start, $length) => implode("\n\n", array_map(static fn ($c) => $c[2]."\n".$c[3], array_slice($cards, $start, $length)));

return "1. Rollen für das Spiel\nEin Satz pro Gruppe; an der Linie schneiden. Sieben Rollen. Ganze Lesung, gleich Spiel, dann Besprechung.\n\n".$section(0, 7)."\n\nLehrkraft: Vollständige Reden und vier Episoden im Lehrerheft. Ein Bruder spricht einen Teil gemeinsamer Worte.\n\n"
    ."2. Reihenfolge der Ereignisse\nVier Karten pro Paar. Ausschneiden und mischen. Einer ordnet Ereignisse, der andere nennt Entscheidung und Folge. Wählt einen Punkt zum Aufhören und eine andere Handlung.\n\n".$section(7, 4)."\n\n"
    ."3. Gedanke, Gefühl oder Handlung?\nSechs Karten pro Paar. Erste drei Empfindungen, letzte drei Handlungen. Lernwunsch, Schmerz durch Vergleich und Wunsch nach fremdem Scheitern unterscheiden. Schädlichen Satz freundlich ersetzen.\n\n".$section(11, 6)."\n\nDer Erfolg anderer kann meinen Wachstumsschritt zeigen. Die Gabe des anderen hebt meine Gaben nicht auf.\nMein ehrlicher und freundlicher Ersatz für den schädlichen Satz: ____________________\nMein konkreter Wachstumsschritt: ____________________\n\n"
    ."4. Vier Informationen — ein Plan\nViererteam. Jeder erhält eine Information und liest sie vor. Plan unter Berücksichtigung aller vier. Felder ganz lassen, ersten Plan nicht löschen.\n\n".$section(17, 4)."\n\nNach dem ersten Plan nennt die Lehrkraft die neue Bedingung. Dann Plan ergänzen.\nWas wir auf dem Plakat behalten und berichtigen: ____________________\nAn wen wir uns wenden und wie wir bitten: ____________________\nWas Dima hilft, seine Gabe zu entwickeln: ____________________\nZweiter Plan nach der neuen Bedingung: Was ergänzen wir: ____________________\n\n"
    ."5. Ohne Abwertung sprechen\nEiner liest Kontext, der andere nennt Gefühl und konkrete Bitte ohne Erniedrigung. Gegenüber: „Ich habe gehört, dass…“. Rollen wechseln und anderen Fall wählen.\n\n".$section(21, 4)."\n\n"
    ."6. Mein nächster guter Schritt\nEchter oder erfundener Fall. Blatt bleibt bei dir. Nur Wachstumsschritt oder Dankbarkeit freiwillig vorlesen.\nWessen Erfolg hat mich verletzt und was fühle ich: ____________________\nWas brauche ich: Wachstum, Gerechtigkeit, Unterstützung: ____________________\nWelche eigenen Gaben und welches Gute kann ich bemerken: ____________________\nWelche schädliche Handlung werde ich nicht tun: ____________________\nWelchen kleinen Wachstums- oder guten Schritt wähle ich: ____________________\nWer hilft und wann tue ich den ersten Schritt: ____________________\n\nHerr, hilf mir, dem anderen nichts Böses zu wünschen. Lehre mich, mich am Guten anderer zu freuen, für meine Gaben zu danken und sie zu entwickeln. Lass mich ehrlich darüber sprechen, was mich verletzt hat, und Gutes tun. Amen.\nSelbst verfasstes Gebet. Du darfst still zuhören.";
