<?php

declare(strict_types=1);

return [
    ['Рассказчик', 'Назови возраст Иосифа, предпочтение отца, зависть братьев и переходы. Заверши горем Иакова и продажей Иосифа Потифару.', 'Erzähler', 'Nenne Josefs Alter, die Bevorzugung durch den Vater, den Neid der Brüder und die Übergänge. Ende mit Jakobs Trauer und Josefs Verkauf an Potifar.', 2],
    ['Иосиф', 'Получаешь одежду, рассказываешь два сна. Потом кладёшь ткань, садишься у места рва. Уходишь с торговцем.', 'Josef', 'Du erhältst das Gewand und erzählst zwei Träume. Dann legst du den Stoff hin und setzt dich an den Ort der Grube. Du gehst mit dem Händler fort.', 2],
    ['Иаков', 'Передай Иосифу ткань. Ответь на второй сон. В финале узнай одежду сына и останься в горе.', 'Jakob', 'Gib Josef den Stoff. Antworte auf den zweiten Traum. Erkenne am Ende das Gewand deines Sohnes und bleibe in Trauer.', 2],
    ['Рувим', 'Скажи: «Не убьем его… не проливайте крови». Ты хочешь вернуть Иосифа отцу. Вернись к пустому рву.', 'Ruben', 'Sage: „Wir wollen ihn nicht töten… vergießt kein Blut.“ Du willst Josef zum Vater zurückbringen. Kehre zur leeren Grube zurück.', 2],
    ['Иуда', 'Предложи продать Иосифа. Полная реплика — в сценарии. Продажа приносит вред брату и семье.', 'Juda', 'Schlage vor, Josef zu verkaufen. Die vollständige Rede steht im Ablauf. Der Verkauf schadet dem Bruder und der Familie.', 2],
    ['Брат', 'Передай общие слова братьев о сне и замысле. В финале принеси одежду отцу. Ты представляешь часть братьев.', 'Bruder', 'Sprich gemeinsame Worte der Brüder über den Traum und den Plan. Bringe am Ende das Gewand zum Vater. Du vertrittst einen Teil der Brüder.', 2],
    ['Торговец', 'На словах рассказчика о продаже подойди к Иосифу. Вместе перейдите к рисунку пути в Египет.', 'Händler', 'Komm zu Josef, wenn der Erzähler vom Verkauf spricht. Geht gemeinsam zum Bild des Weges nach Ägypten.', 2],
    ['Иосиф во рву', 'Быт. 37:23–24. Братья снимают одежду и бросают Иосифа в ров без воды.', 'Josef in der Grube', 'Genesis 37,23–24. Die Brüder nehmen Josef das Gewand ab und werfen ihn in eine Grube ohne Wasser.', 3],
    ['Одежда, сны, зависть', 'Быт. 37:3–11. Отец выделяет Иосифа; братья ненавидят его и завидуют.', 'Gewand, Träume, Neid', 'Genesis 37,3–11. Der Vater bevorzugt Josef; die Brüder hassen ihn und sind neidisch.', 3],
    ['Обман и горе отца', 'Быт. 37:31–36. Одеждой обманывают Иакова; он скорбит. Иосиф продан Потифару в Египте.', 'Täuschung und Trauer des Vaters', 'Genesis 37,31–36. Mit dem Gewand täuschen sie Jakob; er trauert. Josef wird in Ägypten an Potifar verkauft.', 3],
    ['Продажа Иосифа', 'Быт. 37:26–28. Иуда предлагает продажу; Иосиф продан за двадцать сребреников и отправлен в Египет.', 'Josefs Verkauf', 'Genesis 37,26–28. Juda schlägt den Verkauf vor; Josef wird für zwanzig Silberstücke verkauft und nach Ägypten gebracht.', 3],
    ['«Хочу тоже научиться рисовать»', 'Переживание. Желание развить свой навык. Обязательно ли это зависть?', '„Ich möchte auch zeichnen lernen“', 'Empfindung. Wunsch, die eigene Fähigkeit zu entwickeln. Ist das unbedingt Neid?', 4],
    ['«Меня опять сравнили с сестрой»', 'Переживание. Боль от сравнения. О какой справедливой просьбе можно сказать взрослому?', '„Man hat mich wieder mit meiner Schwester verglichen“', 'Empfindung. Schmerz durch den Vergleich. Welche gerechte Bitte kannst du einem Erwachsenen sagen?', 4],
    ['«Пусть её рисунок не выберут»', 'Переживание. Желание чужой неудачи. Какую мысль можно выбрать вместо этого?', '„Hoffentlich wird ihre Zeichnung nicht ausgewählt“', 'Empfindung. Wunsch nach dem Misserfolg eines anderen. Welchen Gedanken kannst du stattdessen wählen?', 4],
    ['«Скажу, что её работа плохая»', 'Действие. Обесценивание. Как признать чувство и не унижать чужую работу?', '„Ich werde sagen, dass ihre Arbeit schlecht ist“', 'Handlung. Abwertung. Wie kannst du das Gefühl anerkennen, ohne eine fremde Arbeit herabzusetzen?', 4],
    ['«Попрошу показать один приём»', 'Действие. Учиться у другого, сохраняя свой путь. Что конкретно попросить?', '„Ich werde um eine Technik bitten“', 'Handlung. Von anderen lernen und den eigenen Weg behalten. Worum kannst du konkret bitten?', 4],
    ['«Поздравлю и продолжу учиться»', 'Действие. Признать чужой труд и свой рост. Какой маленький шаг выбрать?', '„Ich gratuliere und lerne weiter“', 'Handlung. Die Arbeit des anderen und das eigene Wachstum anerkennen. Welchen kleinen Schritt kannst du wählen?', 4],
    ['1. Чужой успех', 'Для общего плаката выбрали Олин рисунок. Учитель похвалил её перед классом. Диме стало завидно: он тоже хотел признания.', '1. Erfolg eines anderen', 'Für das gemeinsame Plakat wurde Oljas Zeichnung gewählt. Die Lehrkraft lobte sie vor der Klasse. Dima wurde neidisch: Auch er wollte Anerkennung.', 6],
    ['2. Неучтённый вклад', 'На плакате использованы Димины фотографии. Подпись фотографа пропущена. Дима вправе попросить признать свой вклад.', '2. Ein übersehener Beitrag', 'Auf dem Plakat sind Dimas Fotos. Die Angabe des Fotografen fehlt. Dima darf darum bitten, seinen Beitrag anzuerkennen.', 6],
    ['3. Кто делал плакат', 'Оля нарисовала картину. Подписи и размещение собирал другой участник. Пока неизвестно, знает ли Оля об отсутствии имени Димы.', '3. Wer das Plakat gestaltet hat', 'Olja zeichnete das Bild. Ein anderer Teilnehmer stellte Beschriftung und Anordnung zusammen. Noch ist unklar, ob Olja vom fehlenden Namen Dimas weiß.', 6],
    ['4. Время и помощь', 'Плакат нужно сдать через 15 минут. Учитель рядом; подпись можно добавить. Перерисовать весь плакат за это время не получится.', '4. Zeit und Hilfe', 'Das Plakat muss in 15 Minuten abgegeben werden. Die Lehrkraft ist in der Nähe; der Name kann ergänzt werden. Das ganze Plakat lässt sich in dieser Zeit nicht neu zeichnen.', 6],
    ['Выбрали чужой рисунок', 'Твой рисунок не выбрали, выбрали рисунок друга. Скажи о своём чувстве и попроси совет по одной технике; признай его успех.', 'Eine fremde Zeichnung wurde gewählt', 'Deine Zeichnung wurde nicht gewählt, die deines Freundes schon. Sprich über dein Gefühl und bitte um Rat zu einer Technik; erkenne seinen Erfolg an.', 7],
    ['Сравнили с сестрой', 'Взрослый говорит: «Вот сестра всё умеет». Попроси говорить о твоём конкретном навыке без сравнения. Не обесценивай сестру.', 'Mit der Schwester verglichen', 'Ein Erwachsener sagt: „Deine Schwester kann doch alles.“ Bitte darum, über deine konkrete Fähigkeit ohne Vergleich zu sprechen. Werte deine Schwester nicht ab.', 7],
    ['Не назвали вклад', 'В общей работе назвали автора рисунка, но забыли твои фотографии. Попроси добавить подпись, сохранив имя автора рисунка.', 'Der Beitrag wurde nicht genannt', 'Bei der gemeinsamen Arbeit wurde die Zeichnerin genannt, deine Fotos wurden vergessen. Bitte darum, deinen Namen zu ergänzen und den der Zeichnerin zu behalten.', 7],
    ['Новая вещь у друга', 'У друга вещь, которую ты тоже хочешь. Не высмеивай её. Назови желание и реши, что ценного уже есть у тебя и чему ты можешь учиться.', 'Eine neue Sache beim Freund', 'Dein Freund hat etwas, das du auch möchtest. Mache es nicht lächerlich. Benenne den Wunsch und überlege, was du schon Wertvolles hast und was du lernen kannst.', 7],
];
