<?php

declare(strict_types=1);

// German adaptation of the owner's Russian pack. Scripture is translated from the supplied text.
return [
    'lesson' => [
        'title' => 'Worte verletzen. Worte heilen',
        'goal' => 'Jugendlichen helfen, die Wirkung ihrer Worte auf andere zu erkennen und ehrlich zu sprechen, ohne jemanden herabzusetzen.',
        'main_idea' => 'Worte können Menschen verletzen, aber auch unterstützen und helfen. Christen lernen, mit Liebe zu sprechen und Verantwortung für ihre Worte zu übernehmen.',
        'short_description' => 'Wie antworte ich, wenn ich wütend bin? Was schreibe ich einem Freund, der verspottet wurde? An Beispielen aus dem Klassenchat lernen Jugendliche, die Wirkung von Worten wahrzunehmen, Probleme respektvoll anzusprechen und einander zu unterstützen. Biblische Grundlage: Jakobus 3,2–10 und Epheser 4,29.',
        'outcomes' => ['Erklären, warum ein scharfer Satz verletzen kann.', 'Eine verletzende Äußerung umformulieren, ohne das eigentliche Problem zu verschweigen.', 'Unterstützende Worte und einen Weg zur Wiedergutmachung vorschlagen.', 'Einen konkreten Schritt für die Woche wählen.'],
        'materials' => ['Bildschirm oder Projektor und ein Gerät für die Leitung.', 'Handy, Tablet oder Computer für Antworten; ein Gerät pro Paar genügt.', 'Bibel oder die Texte aus Jakobus 3,2–10 und Epheser 4,29.'],
        'teacher_notes' => ['Besprechen Sie erfundene Situationen. Persönliche Geschichten werden nur freiwillig erzählt.', 'Lassen Sie die Jugendlichen ihre Wahl erklären. Beim Umformulieren sind verschiedene gute Antworten möglich.', 'Lesen Sie freie Antworten vor der gemeinsamen Anzeige. Die Beispiele dürfen nicht zu neuen Spottanlässen werden.', 'Unterscheiden Sie Unterstützung von Schmeichelei und vom Verschweigen eines Problems. Respekt ermöglicht auch ehrliche und unangenehme Wahrheiten.', 'Wenn tatsächliches Mobbing angesprochen wird, bieten Sie ein persönliches Gespräch nach der Stunde und Unterstützung durch einen vertrauenswürdigen Erwachsenen an.', 'Die persönliche Wahl für die Woche wird nicht auf dem gemeinsamen Bildschirm angezeigt.'],
        'plan' => ['Beginn', 'Die Nachricht wurde gelesen', 'Senden oder ändern', 'Biblische Grundlage', 'Andere Worte', 'Gründe für scharfe Antworten', 'Eine Pause', 'Unterstützung', 'Wiedergutmachung', 'Persönlicher Schritt und Abschluss'],
        'plan_activities' => ['Beitreten und eine kurze Frage zur Wirkung von Worten.', 'Abstimmung über eine gelöschte Nachricht. Was tun mit der Verletzung, die bleibt?', 'Vier Sätze. Eine Antwort wählen und über Spott sprechen.', 'Jakobus 3,5 und Epheser 4,29. Über ehrliches und respektvolles Sprechen nachdenken.', 'Sätze über einen Fehler und eine Verspätung umformulieren. Kurze Dialoge.', 'Gründe auswählen. Den Moment finden, in dem man innehalten kann.', 'Drei Fragen vor einer Antwort. Auf einen Satz anwenden.', 'Ein gutes Wort nach einer schlechten Note und eine Antwort auf Spott im Chat.', 'Die Reihenfolge der Wiedergutmachung nach verletzenden Worten und eine abschließende Situation.', 'Ein Schritt für die Woche. Zur Hauptaussage zurückkehren.'],
    ],
    'screens' => [
        ['title' => 'Worte verletzen. Worte heilen', 'screen_text' => 'Wie wirken unsere Worte auf einen anderen Menschen?', 'student_task' => 'Tritt der Stunde bei und denke über die Frage auf dem Bildschirm nach.', 'teacher_actions' => 'Öffnen Sie den Raum und zeigen Sie den Link oder QR-Code der Website. Nennen Sie beim Beitritt das Thema: „Heute besprechen wir erfundene Situationen und probieren verschiedene Antworten aus.“', 'discussion_question' => 'Kann ein kurzer Satz die Stimmung für den ganzen Tag verändern?', 'conclusion' => 'Heute versuchen wir, die Folgen unserer Worte wahrzunehmen und unsere Antwort bewusst zu wählen.', 'sample_responses' => [], 'options' => []],
        ['title' => 'Die Nachricht wurde schon gelesen', 'screen_text' => 'Du hast einem Freund geschrieben: „Du bist wieder zu nichts zu gebrauchen.“ Die Nachricht wurde schon gelesen. Verschwindet die Verletzung, wenn du sie löschst?', 'student_task' => 'Wähle eine Antwort. Erkläre sie in einem Satz.', 'teacher_actions' => 'Öffnen Sie die Abstimmung für 20 Sekunden. Schließen Sie die Antworten, zeigen Sie das Gruppenergebnis und hören Sie zwei Erklärungen an. Verlangen Sie keine persönlichen Geschichten.', 'discussion_question' => 'Was kann man nach dem Löschen der Nachricht tun?', 'conclusion' => 'Das Löschen macht nicht ungeschehen, was jemand gelesen oder gehört hat. Wir können aber unseren Fehler eingestehen und um Vergebung bitten.', 'sample_responses' => [], 'options' => ['Ja, denn die Nachricht ist weg', 'Nein, die Person hat sie schon gelesen', 'Ich weiß es nicht']],
        ['title' => 'Senden oder ändern', 'screen_text' => "1. „Du kannst überhaupt nichts richtig machen.“\n2. „Es verletzt mich, dass du das gemacht hast. Lass uns darüber sprechen.“", 'student_task' => 'Wähle für jeden Satz: senden, ändern oder nicht senden.', 'teacher_actions' => 'Zeigen Sie die Sätze einzeln. Geben Sie jeweils 15 Sekunden zum Abstimmen. Zeigen Sie nach jedem Satz das Ergebnis und fragen Sie, welches Wort die Wahl beeinflusst hat.', 'discussion_question' => 'Wo geht es um eine Handlung und wo wird der ganze Mensch beurteilt?', 'conclusion' => '„Nichts“ und „kannst nicht“ machen aus einem einzelnen Fehler eine herabsetzende Bewertung der Person. Der zweite Satz kann ein Gespräch über eine Handlung eröffnen.', 'sample_responses' => ['Für den ersten Satz passen „ändern“ oder „nicht senden“.', 'Den zweiten kann man senden, wenn tatsächlich ein Problem besteht und man bereit ist, ruhig darüber zu sprechen.'], 'options' => ['Senden', 'Ändern', 'Nicht senden']],
        ['title' => 'Scherz und Spott', 'screen_text' => "1. „Alle haben es schon verstanden, nur du nicht.“\n2. „Du siehst schrecklich aus.“", 'student_task' => 'Wähle für jeden Satz: senden, ändern oder nicht senden. Erkläre, wie sich die angesprochene Person fühlt.', 'teacher_actions' => 'Öffnen Sie zwei Abstimmungen für jeweils 15 Sekunden. Besprechen Sie, warum ein Lächeln oder das Wort „Scherz“ einen Satz nicht immer harmlos macht. Klären Sie beim zweiten Satz den Zusammenhang: ein ungefragter und unnötiger Kommentar zum Aussehen.', 'discussion_question' => 'Was passiert, wenn alle lachen und eine Person darunter leidet?', 'conclusion' => 'Spott kann einen Menschen herabsetzen. Manchmal ist Schweigen besser. Wenn Hilfe nötig ist, sollte man ruhig und unter vier Augen sprechen.', 'sample_responses' => ['„Wenn du möchtest, erkläre ich es anders.“', 'Über das Aussehen sagt man ohne Anlass besser nichts.'], 'options' => ['Senden', 'Ändern', 'Nicht senden']],
        ['title' => 'Ein kleiner Funke', 'screen_text' => "„Auch die Zunge ist ein kleines Glied und bewirkt viel. Sieh, wie viel ein kleines Feuer entzünden kann!“\nJakobus 3,5 · Übersetzung des bereitgestellten russischen Textes", 'student_task' => 'Höre den Vers und vergleiche Feuer mit einem Streit im Chat.', 'teacher_actions' => 'Lesen Sie Jakobus 3,5. Fassen Sie dann Jakobus 3,6 und 3,9–10 mit eigenen Worten zusammen: Mit derselben Zunge loben wir Gott und können Menschen verletzen, die nach seinem Bild geschaffen sind. Zeigen Sie das Bild des Funkens.', 'discussion_question' => 'Wie wird aus einem Spottwort ein großer Streit?', 'conclusion' => 'Wenige Worte können viele Menschen in einen Streit hineinziehen. Christen übernehmen Verantwortung dafür, wie sie andere ansprechen.', 'sample_responses' => [], 'options' => []],
        ['title' => 'Ein gutes Wort', 'screen_text' => "„Kein verderbliches Wort soll aus eurem Mund kommen, sondern nur ein gutes zur Erbauung im Glauben, damit es den Hörenden Gnade schenkt.“\nEpheser 4,29 · Übersetzung des bereitgestellten russischen Textes", 'student_task' => 'Überlege: Kann man eine unangenehme Wahrheit freundlich sagen?', 'teacher_actions' => 'Lesen Sie den ganzen Vers. Erklären Sie: „Erbauen bedeutet, einem Menschen zu helfen, im Guten zu wachsen.“ Vergleichen Sie: „Du bist verantwortungslos“ und „Du hast dein Versprechen nicht gehalten. Lass uns überlegen, wie wir das in Ordnung bringen.“', 'discussion_question' => 'Wie spricht man ein Problem an und achtet dabei die Person?', 'conclusion' => 'Ein gutes Wort kann ehrlich und streng sein. Es hilft, die Handlung und eine Möglichkeit zur Korrektur zu erkennen.', 'sample_responses' => [], 'options' => []],
        ['title' => 'Ein Fehler bei der gemeinsamen Arbeit', 'screen_text' => 'Ein Freund hat Teile des gemeinsamen Projekts verwechselt. Du möchtest sagen: „Du hast wieder alles vermasselt!“', 'student_task' => 'Schreibe einen Satz, der hilft, den Fehler zu korrigieren, ohne den Freund herabzusetzen.', 'teacher_actions' => 'Geben Sie 45 Sekunden für die Antwort. Lesen Sie die Texte vor der Anzeige. Zeigen Sie zwei oder drei passende Vorschläge. Besprechen Sie, ob sie ein konkretes Problem und ein Hilfsangebot benennen. Laden Sie zwei Freiwillige zu einem kurzen Dialog ein.', 'discussion_question' => 'Nach welcher Antwort möchte man weiterarbeiten?', 'conclusion' => 'Man kann den Fehler benennen und einen nächsten Schritt vorschlagen. Das hilft der Arbeit und bewahrt die Würde des Menschen.', 'sample_responses' => ['„Hier sind die Teile vertauscht. Lass sie uns gemeinsam richtig anordnen.“', '„Diese Variante passt nicht. Probieren wir eine andere?“'], 'options' => []],
        ['title' => 'Zu spät', 'screen_text' => 'Ein Freund ist wieder zu spät gekommen. Du hast zwanzig Minuten gewartet und bist verletzt.', 'student_task' => 'Sprich deinen Ärger an und schlage eine Vereinbarung für das nächste Mal vor.', 'teacher_actions' => 'Geben Sie 45 Sekunden. Zeigen Sie nach dem Lesen zwei oder drei Antworten. Bitten Sie zwei Freiwillige, das Gespräch nachzuspielen. Ist die Bitte verständlich? Werden Worte wie „immer“, „nie“ oder „mit dir geht es nicht“ vermieden?', 'discussion_question' => 'Kann freundliches Sprechen helfen, eigene Grenzen zu benennen?', 'conclusion' => 'Respekt erlaubt uns, klar zu sagen, was uns unangenehm ist, und um eine Änderung der Handlung zu bitten.', 'sample_responses' => ['„Ich habe zwanzig Minuten gewartet und bin enttäuscht. Schreib mir bitte, wenn du dich verspätest.“', '„Pünktlichkeit ist mir wichtig. Lass uns eine Zeit vereinbaren, die für uns beide passt.“'], 'options' => []],
        ['title' => 'Warum eine Antwort scharf wird', 'screen_text' => 'Was bringt Menschen häufig dazu, scharfe Worte zu gebrauchen?', 'student_task' => 'Wähle höchstens zwei Gründe. Du kannst über eine erfundene Person antworten.', 'teacher_actions' => 'Öffnen Sie die Wahl für 25 Sekunden. Zeigen Sie das Gruppenergebnis und hören Sie zwei Erklärungen. Wut und der Wunsch, der Gruppe zu gefallen, können eine Handlung erklären, rechtfertigen aber keine Verletzung.', 'discussion_question' => 'In welchem Moment kann man noch anhalten?', 'conclusion' => 'Wenn man die eigene Wut oder den Wunsch nach Vergeltung bemerkt, kann man eine Pause machen und andere Worte wählen.', 'sample_responses' => [], 'options' => ['War wütend', 'Wollte einen Scherz machen', 'Wollte anderen gefallen', 'Wollte es heimzahlen', 'Hat ohne Nachdenken gesprochen', 'Wollte beweisen, recht zu haben']],
        ['title' => 'Eine Pause vor der Antwort', 'screen_text' => "Ist es wahr?\nMuss ich das jetzt sagen?\nWie sage ich es respektvoll?", 'student_task' => 'Wendet die Fragen auf den Satz „Du kannst nichts“ an.', 'teacher_actions' => 'Zeigen Sie die drei Fragen und geben Sie zehn Sekunden Stille. Besprechen Sie: Der Satz verallgemeinert. Einen konkreten Fehler kann man ruhig benennen. Schlagen Sie ein stilles Gebet vor: „Herr, hilf mir, ohne Bosheit zu antworten.“', 'discussion_question' => 'Welche Frage hilft dir, innezuhalten?', 'conclusion' => 'Eine Pause gibt Zeit, die eigenen Worte zu prüfen. Die Bitte um Gottes Hilfe kann unsere Entscheidung begleiten.', 'sample_responses' => [], 'options' => []],
        ['title' => 'Ein Freund hat eine schlechte Note bekommen', 'screen_text' => 'Ein Freund sagt: „Schon wieder eine schlechte Note. Ich verstehe nichts.“', 'student_task' => 'Schreibe einen ehrlichen Satz, der unterstützt.', 'teacher_actions' => 'Geben Sie 40 Sekunden. Lesen und zeigen Sie einige Antworten. Vergleichen Sie Hilfe mit Verharmlosung („Ist doch egal, vergiss es“) und leeren Versprechen („Alles wird ganz sicher gut“).', 'discussion_question' => 'Welche Worte helfen und welche Handlung kann darauf folgen?', 'conclusion' => 'Unterstützung erkennt die Schwierigkeit an und bietet mögliche Hilfe an.', 'sample_responses' => ['„Ich verstehe, dass du enttäuscht bist. Wollen wir die Aufgabe gemeinsam anschauen?“', '„Eine Note sagt nicht alles darüber, was du kannst.“'], 'options' => []],
        ['title' => 'Spott im gemeinsamen Chat', 'screen_text' => 'Im Chat wird ein Mitschüler wegen seiner Antwort verspottet. Du siehst es. Was tust du?', 'student_task' => 'Wähle eine Handlung und überlege eine kurze unterstützende Nachricht.', 'teacher_actions' => 'Geben Sie 20 Sekunden zum Wählen. Besprechen Sie die Möglichkeiten. Lassen Sie mündlich eine persönliche Nachricht vorschlagen. Bei wiederholtem Mobbing raten Sie zur Hilfe eines vertrauenswürdigen Erwachsenen.', 'discussion_question' => 'Wie unterstützt man jemanden, ohne den Spott fortzusetzen?', 'conclusion' => 'Man kann sich nicht am Spott beteiligen, ruhig widersprechen und die Person unterstützen. Wenn Mobbing anhält, braucht es Hilfe durch einen Erwachsenen.', 'sample_responses' => ['Im Chat: „Bitte ohne Spott. Jeder kann einen Fehler machen.“', 'Persönlich: „Ich habe die Nachrichten gesehen. Du musst damit nicht allein bleiben. Lass uns Hilfe holen.“'], 'options' => ['Ich schreibe noch einen lustigen Kommentar', 'Ich tue nichts', 'Ich mache beim Spott nicht mit und helfe der Person', 'Ich beleidige die Spottenden']],
        ['title' => 'Wenn ich schon verletzt habe', 'screen_text' => 'Wie bringe ich in Ordnung, was mit meinen Worten begonnen hat?', 'student_task' => 'Ordne die Schritte. Schlage danach einen Satz zur Entschuldigung vor.', 'teacher_actions' => 'Geben Sie 30 Sekunden für die Reihenfolge und zeigen Sie das Ergebnis. Besprechen Sie eine Entschuldigung ohne „aber du selbst“. Bitten Sie um zwei Beispiele. Die verletzte Person ist vielleicht noch nicht bereit zu vergeben oder zu sprechen.', 'discussion_question' => 'Was unterscheidet „War doch nur Spaß, sei nicht beleidigt“ von einer Bitte um Vergebung?', 'conclusion' => 'Wir tragen Verantwortung für unsere Worte, bitten um Vergebung und versuchen, den Schaden zu beheben. Sofortige Vergebung darf man nicht verlangen.', 'sample_responses' => ['„Ich habe etwas Verletzendes geschrieben. Bitte verzeih mir. Ich werde im Chat sagen, dass ich falsch gehandelt habe.“'], 'options' => ['Verletzende Worte stoppen', 'Die eigene Handlung eingestehen', 'Um Vergebung bitten', 'Versuchen, den Schaden zu beheben']],
        ['title' => 'Was sage ich jetzt?', 'screen_text' => 'Ein Freund hat seinen Teil des Projekts nicht gemacht. Morgen muss die Arbeit abgegeben werden. Welche Antwort hilft, das Problem zu lösen?', 'student_task' => 'Wähle eine Antwort und erkläre, warum sie passt.', 'teacher_actions' => 'Geben Sie 20 Sekunden und zeigen Sie die Ergebnisse. Lassen Sie erklären, wie die gewählte Antwort das Problem benennt und bei einer Lösung hilft. Damit wird kurz das Lernziel überprüft.', 'discussion_question' => 'Was ist an der Antwort ehrlich und was hilft?', 'conclusion' => 'Wir benennen die konkrete Handlung und schlagen eine Lösung vor, ohne den Respekt zu verlieren.', 'sample_responses' => [], 'options' => ['Du bist wie immer verantwortungslos', 'Nicht schlimm, ich mache alles für dich', 'Dein Teil ist noch nicht fertig. Lass uns überlegen, was du heute noch schaffen kannst']],
        ['title' => 'Mein Schritt für die Woche', 'screen_text' => 'Diese Woche möchte ich versuchen …', 'student_task' => 'Wähle für dich einen Schritt und überlege, wann du ihn umsetzt. Du kannst deine Wahl für dich behalten.', 'teacher_actions' => 'Geben Sie eine Minute für die persönliche Entscheidung. Die Website darf diese Antworten nicht gemeinsam anzeigen. Freiwillige dürfen mündlich nur ihre geplante Handlung nennen. Fragen Sie nicht nach dem Namen der Person, bei der sie sich entschuldigen möchten.', 'discussion_question' => 'In welcher nächsten Situation möchtest du es versuchen?', 'conclusion' => 'Ein kleiner konkreter Schritt hilft, das Gelernte in den Alltag mitzunehmen.', 'sample_responses' => [], 'options' => ['Eine Pause machen, wenn ich wütend bin', 'Bei Spott nicht mitmachen', 'Jemandem ein unterstützendes Wort sagen', 'Für verletzende Worte um Vergebung bitten']],
        ['title' => 'Worte können helfen', 'screen_text' => 'Ich kann Worte wählen, die einem Menschen helfen.', 'student_task' => 'Denke an deinen Schritt für die Woche.', 'teacher_actions' => 'Kehren Sie zur Nachricht am Anfang zurück. Fassen Sie zusammen: Gesagtes wird nicht ungehört, aber wir können vor der Antwort innehalten und Geschehenes wiedergutmachen. Wer möchte, kann mit einem kurzen Gebet abschließen.', 'discussion_question' => '', 'conclusion' => 'Herr, hilf uns, böse Worte zurückzuhalten, den Schmerz anderer wahrzunehmen und mit Liebe zu sprechen. Amen.', 'sample_responses' => [], 'options' => []],
    ],
];
