<?php

declare(strict_types=1);

return [
    'title' => 'Zachäus. Kann man einen Fehler wiedergutmachen?',
    'description' => 'Zachäus wollte Jesus sehen. Die Begegnung mit ihm wurde zum Anfang einer Veränderung. Kinder lernen seine Geschichte kennen und überlegen anhand erfundener Situationen, was sie nach einem Fehler tun können. Mit Antwortmöglichkeiten, Handlungskarten und kurzen Dialogen üben sie, ihre eigene Tat zuzugeben, um Vergebung zu bitten und einen konkreten, machbaren Schritt zur Wiedergutmachung vorzuschlagen. Die Stunde verbindet Gottes Barmherzigkeit mit unserer Verantwortung für den nächsten Schritt.',
    'goals' => ['Erzählen, was sich nach der Begegnung von Zachäus mit Jesus verändert hat.', 'Ein versehentliches Missgeschick von einer bewussten Täuschung unterscheiden.', 'Eine ehrliche Entschuldigung und eine machbare Wiedergutmachung vorschlagen.'],
    'slideQuestions' => [3 => 'Warum war Zachäus auf dem Baum?', 5 => 'Was unterscheidet das von den Worten „Es tut mir leid“?', 6 => 'Wo hört die Figur auf, die Schuld abzuwälzen?', 7 => 'Warum reicht ein Versprechen manchmal nicht?', 8 => 'Wie erhält der Urheber seine Anerkennung zurück?', 10 => 'Was hilft dem Eigentümer tatsächlich?', 11 => 'Was hilft, ein Versprechen einzuhalten?', 12 => 'Wie unterscheidet sich Umkehr von einer Ausrede?'],
    'preparation' => "Lies Lukas 19,1–10 vollständig. Prüfe die zwölf Folien. Drucke vier Handlungskarten pro Paar und ein Arbeitsblatt pro Kind aus. Die Texte können auch von Hand abgeschrieben werden. Bereite Papier und Stifte vor. Für den Dialog über das Buch genügt das Bild; kein echtes Buch wird beschädigt. Bei einer Online-Stunde nutze den gemeinsamen Bildschirm. Die Reihenfolge der Karten kann auch mündlich genannt werden.\n\nEin Zöllner erhob Steuern. Der Text nennt Zachäus einen reichen Oberzöllner. Behaupte nicht, dass jeder Zöllner zwangsläufig stahl. Zachäus verspricht, die Hälfte seines Besitzes den Armen zu geben und Unrecht vierfach zu ersetzen. Das Evangelium berichtet sein Versprechen, nicht eine Geldübergabe. Bild 03 stellt eine mögliche Erfüllung vor. Jesus spricht Zachäus vor diesem Versprechen an. Vergebung und Rettung kann man nicht durch gute Taten kaufen.\n\nVerlange keine persönlichen Bekenntnisse vor der Gruppe. Besprecht erfundene Fälle. Ein Geschädigter ist vielleicht noch nicht bereit zu vergeben oder wieder zu vertrauen. Erkläre den Kindern bei Lukas 19,10, dass Jesus den Menschen sucht, der Rettung braucht. Lies auch Vers 9 über die Rettung des Hauses. Bei ernstem Schaden beende die öffentliche Besprechung einer persönlichen Geschichte und biete ein ruhiges Gespräch mit einem Erwachsenen an. Teilnahme ohne Antwort und ohne Gebet ist möglich. In der ursprünglichen PowerPoint-Datei werden Antworten gemeinsam besprochen; sie sammelt keine Antworten automatisch.",
    'handout' => "Handlungskarten für ein Paar\nSchneidet die vier Karten aus und mischt sie. In Schritt 7 begründet ihr eure Reihenfolge. Wenn der Schaden noch entsteht, muss man ihn zuerst stoppen.\n\nDIE EIGENE TAT ZUGEBEN\nIch benenne, was ich getan habe, und schiebe die Schuld nicht auf andere.\nUM VERGEBUNG BITTEN\nIch erkenne den Schaden an und bitte um Vergebung.\nDEN SCHADEN WIEDERGUTMACHEN\nIch frage, was helfen würde, und schlage etwas Machbares vor.\nANDERS HANDELN\nIch entscheide, was ich in einer ähnlichen Situation ändern werde.\n\nArbeitsblatt\nDu darfst über eine erfundene Figur schreiben. Das Blatt bleibt bei dir; persönliche Antworten müssen nicht vorgelesen werden.\nEin fremdes Bild: Die Figur gibt Saschas Bild als ihr eigenes aus und wird gelobt. Was sagt sie der Lehrkraft? Was sagt sie Sascha? Welche Tat gibt Sascha die Anerkennung zurück?\nEin beschädigtes Buch: Die Figur reißt eine Seite aus einem fremden Buch. Formuliert einen Dialog: die Tat zugeben, um Vergebung bitten, etwas anbieten und nachfragen, Antwort des Eigentümers.\nEin Schritt für diese Woche: Was werde ich oder meine Figur tun? Wann? Wer kann helfen? Der Schritt muss machbar sein. Die Wiedergutmachung wird mit dem Geschädigten besprochen. Vertrauen kann man nicht verlangen.",
    'screens' => [
        ['title' => 'Zachäus', 'text' => 'Kann man einen Fehler wiedergutmachen?', 'task' => 'Überlege anhand des Baumes, worum es in der Geschichte gehen könnte.',
            'notes' => "Leitung: Heute sprechen wir darüber, was man nach einem Fehler tun kann. Schaut auf das Bild: Ein Mann wollte Jesus sehen und kletterte auf einen Baum. Wir raten noch nicht, was für ein Mensch er ist. Wir lernen seine Geschichte kennen. Ihr dürft über eine erfundene Figur antworten. Ihr müsst nichts Persönliches erzählen.\nAufgabe: Überlege anhand des Baumes, worum es in der Geschichte gehen könnte.\nFrage: Kann man eine Tat wiedergutmachen, wenn Zeit vergangen ist?\nFazit: Die Vergangenheit lässt sich nicht rückgängig machen, aber den nächsten Schritt können wir wählen.\nZeit: 30 Sekunden Einstieg; 1 Minute Bild betrachten; 1 Minute Antworten; 30 Sekunden Übergang."],
        ['title' => 'Was ist passiert?', 'text' => "Versehentlich Wasser verschüttet.\nAbgeschrieben und behauptet, selbst gelöst zu haben.", 'task' => 'Ordne die zwei Fälle zu: versehentliches Missgeschick oder bewusste Täuschung.',
            'notes' => "Leitung: Stellt euch zwei Fälle vor. Lena stößt versehentlich an ein Glas und Wasser läuft auf ein fremdes Heft. Wanja schreibt die Lösung ab und sagt, er habe sie selbst gefunden. Was unterscheidet diese Taten? In beiden Fällen kann jemand einen Schaden erleiden, aber die Absichten unterscheiden sich. Was kann jede Figur nun tun? Auch ein Missgeschick muss man anerkennen und helfen, seine Folgen zu beheben.\nAuswahl: Versehentliches Missgeschick / Bewusste Täuschung.\nFrage: Muss man in beiden Fällen etwas wiedergutmachen?\nOrientierung: Das Wasser wurde versehentlich verschüttet, muss aber aufgewischt werden. Die Täuschung muss zugegeben werden.\nFazit: Auch nach einem Missgeschick tragen wir Verantwortung für die Folgen.\nZeit: Je 1 Minute für Fälle, Vergleich im Paar, Antworten und Wiedergutmachung."],
        ['title' => 'Ein Mann auf dem Baum', 'text' => 'Zachäus wollte Jesus sehen.', 'task' => 'Finde im Bild, was Zachäus hinderte und was er tat.',
            'notes' => "Leitung: Jesus ging durch Jericho. Dort lebte der reiche Oberzöllner Zachäus. Zöllner erhoben Steuern. Zachäus wollte Jesus sehen, konnte aber wegen der Menge nichts sehen: Er war klein. Er lief voraus und kletterte auf einen Baum. Findet ihn im Bild. Was hinderte ihn? Welche Lösung fand er?\nFrage: Warum war Zachäus auf dem Baum?\nFazit: Er war klein und die Menge versperrte ihm die Sicht auf Jesus.\nZeit: Je 1 Minute Lukas 19,1–4 lesen, erklären, im Bild suchen und antworten."],
        ['title' => 'Eine unerwartete Einladung', 'text' => 'Jesus ruft Zachäus beim Namen und will in sein Haus kommen.', 'task' => 'Wähle, wer die Begegnung zuerst vorgeschlagen hat.',
            'notes' => "Leitung: Jesus blieb stehen, sah Zachäus an und rief ihn beim Namen. Er sagte, dass er heute in sein Haus kommen müsse. Zachäus stieg schnell herunter und nahm ihn mit Freude auf. Die Leute murrten, weil Jesus zu einem Menschen kam, den sie für einen Sünder hielten. Wer schlug die Begegnung zuerst vor? Findet die Antwort im gelesenen Text. Das Versprechen von Zachäus kommt erst später.\nAuswahl: Jesus / Zachäus / Die Menge.\nFrage: Hatte Zachäus schon versprochen, alles wiedergutzumachen, als Jesus ihn rief?\nFazit: Jesus kommt zuerst zu einem Menschen, den andere verurteilen.\nZeit: Je 1 Minute Lukas 19,5–7 lesen, wählen, mit dem Text begründen und Fazit."],
        ['title' => 'Das Versprechen von Zachäus', 'text' => "Die Hälfte des Besitzes den Armen.\nDas Unrecht vierfach ersetzen.", 'task' => 'Nenne die zwei konkreten Versprechen von Zachäus.',
            'notes' => "Leitung: Hört nun, was Zachäus sagt. Er verspricht, die Hälfte seines Besitzes den Armen zu geben. Wenn er jemandem Unrecht getan hat, will er es vierfach ersetzen. Vierfach heißt viermal so viel. Im Bild stellt sich der Künstler vor, wie Zachäus sein Versprechen erfüllen könnte. Das Evangelium berichtet in diesem Vers das Versprechen selbst. Welche zwei Entscheidungen haben wir gehört?\nFrage: Was unterscheidet das von den Worten „Es tut mir leid“?\nFazit: Umkehr zeigt sich in der Entscheidung, das eigene Handeln zu ändern.\nZeit: Je 1 Minute Lukas 19,8 lesen, Versprechen erklären, Antworten und Fazit."],
        ['title' => 'Worte und Taten', 'text' => "„Entschuldige, aber du bist selbst schuld“.\n„Ich habe gelogen. Entschuldige. Ich werde die Wahrheit sagen“.", 'task' => 'Erklärt im Paar, welcher Satz Verantwortung anerkennt.',
            'notes' => "Leitung: Vergleicht die zwei Sätze. Im ersten sagt die Figur „Entschuldige“, beschuldigt aber gleich den anderen. Im zweiten benennt sie ihre Täuschung und den nächsten Schritt. Besprecht im Paar, welcher Satz Verantwortung anerkennt und warum. Verbessert nun den ersten Satz ohne Beschuldigung. Es geht darum, die eigene Tat zu benennen und eine machbare Wiedergutmachung vorzuschlagen.\nFrage: Wo hört die Figur auf, die Schuld abzuwälzen?\nOrientierung: Der zweite Satz benennt die Täuschung und den nächsten Schritt.\nFazit: Eine ehrliche Entschuldigung benennt die eigene Tat.\nZeit: 1 Minute Sätze lesen; 2 Minuten Paargespräch; 1 Minute zwei Antworten; 1 Minute neue Formulierung."],
        ['title' => 'Der nächste Schritt', 'text' => 'Stellt die Karten in eine sinnvolle Reihenfolge und erklärt eure Entscheidung.', 'task' => 'Stellt die Karten in eine sinnvolle Reihenfolge.',
            'notes' => "Leitung: Vor euch liegen vier Karten. Stellt eine Reihenfolge zusammen, die ihr erklären könnt. Was gibt die Figur zu? Wie bittet sie um Vergebung? Wie schlägt sie Wiedergutmachung vor? Was ändert sie beim nächsten Mal? Wir brauchen keine einzig gültige, starre Reihenfolge. Wenn der Schaden noch entsteht, muss man ihn zuerst stoppen und dem Geschädigten helfen. Nach dem Gespräch betrachten wir die Merkhilfe.\nFrage: Warum reicht ein Versprechen manchmal nicht?\nFazit: Eine Entschuldigung wird durch konkrete Taten fortgesetzt.\nZeit: 30 Sekunden Karten verteilen; 1 Minute ordnen; 1,5 Minuten begründen; 1 Minute Merkhilfe zeigen.\nVor der Antwort benutzt die gemischten Karten. Die ursprüngliche Folie 7 wird erst nach dem Ordnen gezeigt: Sie enthält bereits eine mögliche Reihenfolge."],
        ['title' => 'Eine fremde Arbeit', 'text' => "Du hast ein fremdes Bild als dein eigenes ausgegeben.\nDie Lehrkraft hat dich gelobt.", 'task' => 'Überlege, was du der Lehrkraft und dem Urheber des Bildes sagen kannst.',
            'notes' => "Leitung: Eine erfundene Figur zeigt ein fremdes Bild und sagt, sie habe es selbst gemalt. Die Lehrkraft lobt sie. Wie kann sie dem Urheber die verdiente Anerkennung zurückgeben? Findet zwei kurze Sätze: einen für die Lehrkraft, einen für den Urheber. Die Worte können schwerfallen, aber die Wahrheit beginnt die Wiedergutmachung.\nFrage: Wie kann man dem Urheber die Anerkennung zurückgeben?\nOrientierung: „Das ist Saschas Bild. Ich habe fälschlich gesagt, es sei meines. Entschuldigen Sie bitte“.\nFazit: Man kann die Wahrheit sagen und den tatsächlichen Urheber nennen.\nZeit: Je 1 Minute Fall lesen, Sätze überlegen, Antworten hören und besprechen."],
        ['title' => 'Kann Vertrauen zurückkehren?', 'text' => 'Dein Freund möchte dir seine Sache noch nicht wieder leihen.', 'task' => 'Wähle eine Antwort und erkläre sie.',
            'notes' => "Leitung: Die Figur hat bereits um Vergebung gebeten, aber der Freund möchte ihr seine Sache noch nicht wieder leihen. Wählt eine Antwort und erklärt sie. Kann die Figur verlangen, dass man ihr sofort vertraut? Wir können Verantwortung für unsere Versprechen übernehmen und sie halten. Die Entscheidung des anderen müssen wir respektieren. Vertrauen kehrt manchmal allmählich zurück.\nAuswahl: Vertrauen verlangen / Zeit geben und Versprechen halten / Wieder ohne Erlaubnis nehmen.\nFrage: Können wir jemanden zwingen zu vergeben?\nFazit: Wir verantworten unsere Taten und respektieren die Entscheidung des anderen.\nZeit: Je 1 Minute wählen, begründen, Vertrauen besprechen und Fazit."],
        ['title' => 'Ein beschädigtes Buch', 'text' => "Du hast ein fremdes Buch beschädigt.\nWas sagst du? Was schlägst du vor?", 'task' => 'Spielt einen kurzen Dialog zum Bild: Entschuldigung und Wiedergutmachung.',
            'notes' => "Leitung: Zwei Kinder besprechen ein beschädigtes Buch. Wir spielen nur das Gespräch. Die erste Figur benennt die Tat, bittet um Vergebung und schlägt eine Lösung vor. Die zweite antwortet als Eigentümer. Sie kann sagen: „Es ärgert mich, dass das Buch zerrissen ist. Fragen wir einen Erwachsenen, wie wir es wiederherstellen können“. Reicht Reparieren oder braucht es Ersatz? Das besprechen Eigentümer und Erwachsener gemeinsam.\nFrage: Was hilft dem Eigentümer tatsächlich?\nOrientierung: „Ich habe die Seite zerrissen. Entschuldige. Lass uns mit einem Erwachsenen überlegen, wie wir das Buch wiederherstellen können“.\nFazit: Wiedergutmachung berücksichtigt die Bedürfnisse des Geschädigten.\nZeit: 30 Sekunden Rollen verteilen; 1 Minute Vorbereitung; 1,5 Minuten Dialog; 1 Minute Lösung besprechen."],
        ['title' => 'Ein Schritt', 'text' => "In dieser Woche kann ich …\nzugeben • zurückgeben • wiedergutmachen", 'task' => 'Wähle einen machbaren persönlichen Schritt oder denke dir ein Beispiel für eine Figur aus.',
            'notes' => "Leitung: Schreibt einen kleinen Schritt auf eure Karte. Ihr dürft über euch oder eine erfundene Figur schreiben. Nennt, was sie konkret tun wird und wann. Zum Beispiel morgen eine genommene Sache zurückgeben oder der Lehrkraft die Wahrheit über das Bild sagen. Behaltet die Karte. Wir lesen persönliche Antworten nicht laut vor. Wer kann bei diesem Schritt helfen?\nFrage: Was hilft, ein Versprechen einzuhalten?\nFazit: Man kann mit einer ehrlichen Tat beginnen.\nZeit: 30 Sekunden erklären; 1,5 Minuten persönliche Notiz; 1 Minute Machbarkeit prüfen."],
        ['title' => 'Eine Begegnung verändert das Leben', 'text' => '„Der Menschensohn ist gekommen, das Verlorene zu suchen und zu retten“', 'task' => 'Vervollständige den Satz: „Nach einem Fehler kann ich …“',
            'notes' => "Leitung: Kehren wir zu Zachäus zurück. Jesus sprach ihn an, bevor das Versprechen der Wiedergutmachung ausgesprochen wurde. Seine Barmherzigkeit gab Zachäus Hoffnung auf Veränderung. Umkehr bedeutet, sich Gott zuzuwenden, das eigene Unrecht anzuerkennen und anders zu handeln. Wer möchte, beendet den Satz „Nach einem Fehler kann ich …“. Man darf auch nur zuhören. Auf Wunsch beten wir: „Herr, hilf uns, die Wahrheit zu sagen und Schaden wiedergutzumachen“.\nFrage: Wie unterscheidet sich Umkehr von einer Ausrede?\nFazit: Jesus gibt Hoffnung und wir lernen, unsere Taten zu verantworten.\nZeit: 30 Sekunden Lukas 19,9–10 lesen; 1 Minute Abschlussantworten; 30 Sekunden Abschluss oder Gebet."],
    ],
];
