<?php

declare(strict_types=1);

namespace Tests\Integration;

use App\Application\Runtime\RuntimeService;
use App\Application\Studio\StudioService;
use App\Models\LessonMaterial;
use App\Models\LessonVersion;
use App\Models\SessionAnswer;
use App\Models\SessionCommandReceipt;
use App\Models\TeachingSession;
use Illuminate\Database\Connection;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Symfony\Component\Process\Process;
use Tests\Support\RuntimeConcurrencyGuard;
use Tests\TestCase;

/** Real independent PHP connections; no RefreshDatabase transaction can hide fixtures from workers. */
final class RuntimeConcurrencyTest extends TestCase
{
    private ?Connection $database = null;

    private ?string $materialId = null;

    private ?string $sessionId = null;

    private ?string $owner = null;

    private ?string $runId = null;

    private ?string $directory = null;

    private array $participants = [];

    private array $processes = [];

    private RuntimeService $runtime;

    protected function setUp(): void
    {
        parent::setUp();
        if (PHP_OS_FAMILY === 'Windows' || ! in_array(config('database.default'), ['mysql', 'mariadb'], true)) {
            $this->markTestSkipped('Real concurrency requires Linux and the dedicated MariaDB 10.6 CI database.');
        }
        $this->database = RuntimeConcurrencyGuard::database($this->app);
        $version = $this->database->selectOne('SELECT VERSION() AS version')->version;
        if (! preg_match('/\A10\.6\..*MariaDB/', $version)) {
            $this->markTestSkipped('This integration suite observes real MariaDB 10.6 InnoDB lock waits.');
        }
        $this->assertSame(0, $this->database->transactionLevel(), 'Worker fixtures must be committed.');
        // Additive setup only. Never migrate:fresh/reset or truncate unrelated rows.
        $this->assertSame(0, Artisan::call('migrate', ['--force' => true, '--no-interaction' => true]));
        $this->runId = (string) Str::uuid();
        $this->owner = (string) Str::uuid();
        $this->directory = RuntimeConcurrencyGuard::directory($this->runId);
        $mask = umask(0077);
        try {
            $this->assertTrue(mkdir($this->directory, 0700));
        } finally {
            umask($mask);
        }
        $this->runtime = $this->app->make(RuntimeService::class);
        $material = $this->app->make(StudioService::class)->create($this->owner, $this->document());
        $this->materialId = $material->id;
        $session = $this->runtime->start($this->owner, $material->id, $material->revision, 'ru');
        $this->sessionId = $session['id'];
        foreach (['First', 'Second', 'Existing'] as $name) {
            $participant = $this->runtime->join($session['joinCode'], $name, [])['participant']['id'];
            $this->participants[] = $participant;
            $this->runtime->answer($this->sessionId, $participant, 'first', 'single',
                ['stageId' => 'first', 'blockId' => 'single', 'value' => ['optionId' => 'a']]);
        }
        $this->runtime->command($this->owner, $this->sessionId, (string) Str::uuid(), 1, 'block.open', ['blockId' => 'free']);
        $this->runtime->answer($this->sessionId, $this->participants[0], 'first', 'free',
            ['stageId' => 'first', 'blockId' => 'free', 'value' => ['text' => 'Fixture answer']]);
    }

    protected function tearDown(): void
    {
        try {
            foreach ($this->processes as $process) {
                if ($process->isRunning()) {
                    $process->stop(1);
                }
            }
            if ($this->database !== null && $this->database->transactionLevel() > 0) {
                $this->database->rollBack();
            }
            if ($this->materialId !== null) {
                RuntimeConcurrencyGuard::database($this->app);
                DB::transaction(function (): void {
                    // UUIDs and owner are generated by this test, never supplied by a worker.
                    if ($this->sessionId !== null) {
                        TeachingSession::query()->whereKey($this->sessionId)->where('owner_key', $this->owner)->delete();
                    }
                    LessonMaterial::query()->whereKey($this->materialId)->where('owner_key', $this->owner)->update(['current_version_id' => null]);
                    LessonVersion::query()->where('lesson_material_id', $this->materialId)
                        ->whereHas('material', fn ($query) => $query->where('owner_key', $this->owner))->delete();
                    LessonMaterial::query()->whereKey($this->materialId)->where('owner_key', $this->owner)->delete();
                });
            }
            if ($this->directory !== null && is_dir($this->directory)) {
                $directory = RuntimeConcurrencyGuard::privateDirectory($this->runId);
                foreach (scandir($directory) as $entry) {
                    if ($entry !== '.' && $entry !== '..') {
                        $this->assertFalse(is_dir($directory.'/'.$entry), 'Barrier cleanup only removes generated files.');
                        unlink($directory.'/'.$entry);
                    }
                }
                rmdir($directory);
            }
        } finally {
            parent::tearDown();
        }
    }

    public function test_two_participants_compete_for_last_role_slot_with_one_winner_and_preserved_answers(): void
    {
        $this->runtime->answer($this->sessionId, $this->participants[2], 'first', 'roles',
            ['stageId' => 'first', 'blockId' => 'roles', 'value' => ['roleId' => 'a']]);
        $before = $this->answers();
        $sessionBefore = TeachingSession::findOrFail($this->sessionId)->getAttributes();
        $receiptsBefore = $this->receipts()->count();
        $results = $this->race(array_map(fn (string $id): array => ['kind' => 'role', 'participantId' => $id], array_slice($this->participants, 0, 2)));
        $this->assertEqualsCanonicalizing([200, 409], array_column($results, 'status'));
        $loser = array_search(409, array_column($results, 'status'), true);
        $winner = 1 - $loser;
        $this->assertSame('role_full', $results[$loser]['code']);
        $roles = SessionAnswer::query()->where('teaching_session_id', $this->sessionId)->where('block_id', 'roles')->get();
        $this->assertCount(2, $roles);
        $this->assertEqualsCanonicalizing([$this->participants[2], $this->participants[$winner]], $roles->pluck('session_participant_id')->all());
        foreach ($roles as $role) {
            $this->assertSame(['roleId' => 'a'], $role->value);
            $this->assertSame(1, $role->revision);
        }
        $this->assertSame(count($before) + 1, count($this->answers()));
        $this->assertPriorAnswersUnchanged($before);
        $this->assertSame($sessionBefore, TeachingSession::findOrFail($this->sessionId)->getAttributes());
        $this->assertSame($receiptsBefore, $this->receipts()->count());
        $state = $this->runtime->teacher($this->owner, $this->sessionId);
        $roleView = collect($state['publicStage']['blocks'])->firstWhere('id', 'roles');
        $this->assertSame(['roleId' => 'a', 'used' => 2, 'capacity' => 2], $roleView['runtime']['availability'][0]);
    }

    public function test_concurrent_identical_command_receipts_apply_moderation_exactly_once(): void
    {
        $before = $this->answers();
        $answer = SessionAnswer::query()->where('teaching_session_id', $this->sessionId)->where('block_id', 'free')->firstOrFail();
        $commandId = (string) Str::uuid();
        $session = TeachingSession::findOrFail($this->sessionId);
        $receiptsBefore = $this->receipts()->count();
        $operation = ['kind' => 'command', 'commandId' => $commandId, 'expectedRevision' => $session->revision,
            'action' => 'answer.moderate', 'payload' => ['answerId' => $answer->id, 'expectedAnswerRevision' => 1, 'status' => 'approved', 'displayText' => 'Approved fixture']];
        $results = $this->race([$operation, $operation]);
        $this->assertSame([200, 200], array_column($results, 'status'));
        $this->assertSame([$commandId, $commandId], array_column($results, 'acknowledgedCommandId'));
        $this->assertSame([$session->revision + 1, $session->revision + 1], array_column($results, 'revision'));
        $this->assertSame($receiptsBefore + 1, $this->receipts()->count());
        $this->assertSame(1, $this->receipts()->where('command_id', $commandId)->count());
        $answer->refresh();
        $this->assertSame(2, $answer->revision);
        $this->assertSame('approved', $answer->moderation_status);
        $this->assertSame('Approved fixture', $answer->display_text);
        $this->assertSame(['text' => 'Fixture answer'], $answer->value);
        $this->assertFalse($answer->published);
        $this->assertSame(count($before), count($this->answers()));
        unset($before[$answer->id]);
        $this->assertPriorAnswersUnchanged($before);
        $this->assertSame($session->revision + 1, $session->fresh()->revision);
        $this->assertSame('running', $session->fresh()->status);
        $this->assertSame('first', $session->fresh()->current_stage_id);
    }

    public function test_distinct_commands_with_same_revision_have_one_winner_without_answer_or_lifecycle_changes(): void
    {
        $before = $this->answers();
        $session = TeachingSession::findOrFail($this->sessionId);
        $receiptsBefore = $this->receipts()->count();
        $operations = array_map(fn (string $text): array => ['kind' => 'command', 'commandId' => (string) Str::uuid(),
            'expectedRevision' => $session->revision, 'action' => 'message.set', 'payload' => ['text' => $text]], ['First fixture message', 'Second fixture message']);
        $results = $this->race($operations);
        $this->assertEqualsCanonicalizing([200, 409], array_column($results, 'status'));
        $loser = array_search(409, array_column($results, 'status'), true);
        $winner = 1 - $loser;
        $this->assertSame('revision_conflict', $results[$loser]['code']);
        $this->assertSame($operations[$winner]['commandId'], $results[$winner]['acknowledgedCommandId']);
        $this->assertSame($receiptsBefore + 1, $this->receipts()->count());
        $this->assertSame(1, $this->receipts()->where('command_id', $operations[$winner]['commandId'])->count());
        $this->assertSame(0, $this->receipts()->where('command_id', $operations[$loser]['commandId'])->count());
        $session->refresh();
        $this->assertSame($operations[$winner]['payload']['text'], $session->message);
        $this->assertSame($operations[$winner]['expectedRevision'] + 1, $session->revision);
        $this->assertSame('running', $session->status);
        $this->assertSame('first', $session->current_stage_id);
        $this->assertSame($before, $this->answers());
    }

    private function race(array $operations): array
    {
        $this->privateFile('fixture.json', json_encode(['ownerKey' => $this->owner, 'sessionId' => $this->sessionId,
            'participantIds' => $this->participants, 'operations' => $operations], JSON_THROW_ON_ERROR));
        $config = $this->database->getConfig();
        // Explicit environment prevents .env/config cache from choosing another database.
        // Credentials are inherited environment values, never argv or test failure output.
        $environment = ['APP_ENV' => 'testing', 'APP_DEBUG' => 'false', 'APP_KEY' => config('app.key'),
            'APP_CONFIG_CACHE' => $this->directory.'/unused-config-cache.php', 'DB_CONNECTION' => $config['driver'],
            'DB_HOST' => $config['host'], 'DB_PORT' => (string) ($config['port'] ?? 3306), 'DB_DATABASE' => 'lessons_test',
            'DB_USERNAME' => $config['username'], 'DB_PASSWORD' => $config['password'], 'DB_URL' => '', 'DB_SOCKET' => '',
            'CACHE_STORE' => 'array', 'SESSION_DRIVER' => 'array', 'QUEUE_CONNECTION' => 'sync', 'LOG_CHANNEL' => 'null'];
        $parentId = (int) $this->database->selectOne('SELECT CONNECTION_ID() AS id')->id;
        $this->database->beginTransaction();
        try {
            $this->database->table('teaching_sessions')->where('id', $this->sessionId)->lockForUpdate()->first();
            foreach ([0, 1] as $index) {
                $process = new Process([PHP_BINARY, base_path('tests/Support/runtime_concurrency_worker.php')], base_path(), $environment,
                    json_encode(['runId' => $this->runId, 'worker' => $index], JSON_THROW_ON_ERROR), 45);
                $process->start();
                $this->processes[] = $process;
            }
            $this->waitUntil(fn (): bool => is_file($this->directory.'/ready-0') && is_file($this->directory.'/ready-1'), 'Both PHP workers must reach the start barrier.');
            $workerIds = [(int) file_get_contents($this->directory.'/ready-0'), (int) file_get_contents($this->directory.'/ready-1')];
            $this->assertCount(3, array_unique([$parentId, ...$workerIds]), 'Parent and workers must use independent real connections.');
            $this->privateFile('go', 'start');
            // Observe both live RuntimeService transactions blocked by our fixture row.
            // Merely starting processes close together would not establish real overlap.
            $this->waitUntil(function () use ($workerIds, $parentId): bool {
                $waiting = $this->database->select('SELECT DISTINCT requesting.trx_mysql_thread_id AS connection_id
                    FROM information_schema.INNODB_LOCK_WAITS waits
                    JOIN information_schema.INNODB_TRX requesting ON requesting.trx_id = waits.requesting_trx_id
                    JOIN information_schema.INNODB_TRX blocking ON blocking.trx_id = waits.blocking_trx_id
                    WHERE blocking.trx_mysql_thread_id = ? AND requesting.trx_mysql_thread_id IN (?, ?)', [$parentId, ...$workerIds]);

                return count($waiting) === 2;
            }, 'Both RuntimeService operations must overlap in observed InnoDB lock waits.');
        } finally {
            $this->database->rollBack();
        }
        $results = [];
        foreach ($this->processes as $process) {
            $this->assertSame(0, $process->wait(), 'Isolated worker must finish without a masked infrastructure failure.');
            $results[] = json_decode($process->getOutput(), true, flags: JSON_THROW_ON_ERROR);
        }
        $this->assertSame($workerIds, array_column($results, 'connectionId'));

        return $results;
    }

    private function waitUntil(callable $condition, string $message): void
    {
        $deadline = microtime(true) + 15;
        do {
            clearstatcache();
            foreach ($this->processes as $process) {
                $this->assertTrue($process->isRunning(), 'Workers must remain alive until their concurrent operations are released.');
            }
            if ($condition()) {
                return;
            }
            usleep(100_000);
        } while (microtime(true) < $deadline);
        $this->fail($message);
    }

    private function privateFile(string $name, string $contents): void
    {
        $file = fopen($this->directory.'/'.$name, 'x');
        $this->assertNotFalse($file);
        try {
            $this->assertTrue(chmod($this->directory.'/'.$name, 0600));
            $this->assertSame(strlen($contents), fwrite($file, $contents));
        } finally {
            fclose($file);
        }
    }

    private function answers(): array
    {
        return SessionAnswer::query()->where('teaching_session_id', $this->sessionId)->orderBy('id')->get()
            ->mapWithKeys(fn (SessionAnswer $answer): array => [$answer->id => $answer->getAttributes()])->all();
    }

    private function assertPriorAnswersUnchanged(array $before): void
    {
        $after = $this->answers();
        foreach ($before as $id => $answer) {
            $this->assertSame($answer, $after[$id]);
        }
    }

    private function receipts()
    {
        return SessionCommandReceipt::query()->where('teaching_session_id', $this->sessionId);
    }

    private function document(): array
    {
        $block = fn (string $id, string $type, array $content, array $config = []): array => [
            'id' => $id, 'type' => 'core.'.$type, 'schemaVersion' => 1, 'content' => ['ru' => $content],
            'config' => $config, 'solution' => null, 'teacherNotes' => ['ru' => ''],
        ];

        return ['id' => 'concurrency-fixture', 'schemaVersion' => 1, 'defaultLocale' => 'ru', 'locales' => ['ru'],
            'content' => ['ru' => ['title' => 'Runtime concurrency fixture '.$this->runId]], 'stages' => [
                ['id' => 'first', 'content' => ['ru' => ['title' => 'First']], 'blocks' => [
                    $block('single', 'single-choice', ['question' => 'Choose', 'options' => [['optionId' => 'a', 'text' => 'A'], ['optionId' => 'b', 'text' => 'B']]]),
                    $block('roles', 'roles', ['text' => 'Choose role', 'roles' => [['roleId' => 'a', 'text' => 'A'], ['roleId' => 'b', 'text' => 'B']]], ['capacities' => ['a' => 2, 'b' => 2]]),
                    $block('free', 'free-response', ['question' => 'Write'], ['maxLength' => 100]),
                ]],
            ]];
    }
}
