<?php

declare(strict_types=1);

// German downloads supplement immutable source packs.
return [
    'sourceFiles' => [
        'neighbor-plan-de-v1' => 'neighbor',
        'neighbor-plan-ru-v1' => 'neighbor',
        'neighbor-presentation-ru-v1' => 'neighbor',
        'neighbor-presentation-ru-v2' => 'neighbor',
        'words-file-1-ru-v1' => 'words',
        'words-file-2-ru-v1' => 'words',
        'words-file-3-ru-v1' => 'words',
        'words-file-4-ru-v1' => 'words',
        'words-file-5-ru-v1' => 'words',
        'words-file-3-ru-v2' => 'words',
        'words-file-6-ru-v2' => 'words',
        'words-file-7-ru-v2' => 'words',
        'zakkhei-file-1-ru-v1' => 'zakkhei',
        'zakkhei-file-2-ru-v1' => 'zakkhei',
        'zakkhei-file-3-ru-v1' => 'zakkhei',
        'zakkhei-file-4-ru-v1' => 'zakkhei',
        'zakkhei-file-5-ru-v1' => 'zakkhei',
        'zakkhei-file-3-ru-v2' => 'zakkhei',
        'zakkhei-file-4-ru-v2' => 'zakkhei',
        'zakkhei-file-5-ru-v2' => 'zakkhei',
        'judge-file-1-ru-v1' => 'judge',
        'judge-file-2-ru-v1' => 'judge',
        'judge-file-3-ru-v1' => 'judge',
        'judge-file-4-ru-v1' => 'judge',
        'judge-file-5-ru-v1' => 'judge',
        'judge-file-3-ru-v2' => 'judge',
        'judge-file-4-ru-v2' => 'judge',
        'judge-file-5-ru-v2' => 'judge',
        'sheep-file-1-ru-v1' => 'sheep',
        'sheep-file-2-ru-v1' => 'sheep',
        'sheep-file-3-ru-v1' => 'sheep',
        'sheep-file-4-ru-v1' => 'sheep',
        'sheep-file-5-ru-v1' => 'sheep',
        'sheep-file-3-ru-v2' => 'sheep',
        'sheep-file-4-ru-v2' => 'sheep',
        'sheep-file-5-ru-v2' => 'sheep',
        'talent-file-1-ru-v1' => 'talent',
        'talent-file-2-ru-v1' => 'talent',
        'talent-file-3-ru-v1' => 'talent',
        'talent-file-4-ru-v1' => 'talent',
        'talent-file-5-ru-v1' => 'talent',
        'talent-file-3-ru-v2' => 'talent',
        'talent-file-4-ru-v2' => 'talent',
        'talent-file-5-ru-v2' => 'talent',
        'anger-file-lesson-docx-v1' => 'anger',
        'anger-file-lesson-pdf-v1' => 'anger',
        'anger-file-slides-v1' => 'anger',
        'anger-file-handout-docx-v1' => 'anger',
        'anger-file-handout-pdf-v1' => 'anger',
        'choices-file-1-ru-v1' => 'choices',
        'choices-file-2-ru-v1' => 'choices',
        'choices-file-3-ru-v1' => 'choices',
        'choices-file-4-ru-v1' => 'choices',
        'choices-file-5-ru-v1' => 'choices',
        'envy-file-lesson-docx-v1' => 'envy',
        'envy-file-lesson-pdf-v1' => 'envy',
        'envy-file-slides-v1' => 'envy',
        'envy-file-handout-docx-v1' => 'envy',
        'envy-file-handout-pdf-v1' => 'envy',
        'forgiveness-file-1-ru-v1' => 'forgiveness',
        'forgiveness-file-2-ru-v1' => 'forgiveness',
        'forgiveness-file-3-ru-v1' => 'forgiveness',
        'forgiveness-file-4-ru-v1' => 'forgiveness',
        'forgiveness-file-5-ru-v1' => 'forgiveness',
        'friends-file-1-ru-v1' => 'friends',
        'friends-file-2-ru-v1' => 'friends',
        'friends-file-3-ru-v1' => 'friends',
        'friends-file-4-ru-v1' => 'friends',
        'friends-file-5-ru-v1' => 'friends',
        'joseph-file-lesson-docx-v1' => 'joseph',
        'joseph-file-lesson-pdf-v1' => 'joseph',
        'joseph-file-slides-v1' => 'joseph',
        'joseph-file-handout-docx-v1' => 'joseph',
        'joseph-file-handout-pdf-v1' => 'joseph',
        'peter-file-lesson-docx-v1' => 'peter',
        'peter-file-lesson-pdf-v1' => 'peter',
        'peter-file-slides-v1' => 'peter',
        'peter-file-handout-docx-v1' => 'peter',
        'peter-file-handout-pdf-v1' => 'peter',
        'pressure-file-lesson-docx-v1' => 'pressure',
        'pressure-file-lesson-pdf-v1' => 'pressure',
        'pressure-file-slides-v1' => 'pressure',
        'pressure-file-handout-docx-v1' => 'pressure',
        'pressure-file-handout-pdf-v1' => 'pressure',
        'thanks-file-1-ru-v1' => 'spasibo',
        'thanks-file-2-ru-v1' => 'spasibo',
        'thanks-file-3-ru-v1' => 'spasibo',
        'thanks-file-4-ru-v1' => 'spasibo',
        'thanks-file-5-ru-v1' => 'spasibo',
        'fear-file-1-ru-v1' => 'strakh',
        'fear-file-2-ru-v1' => 'strakh',
        'fear-file-3-ru-v1' => 'strakh',
        'fear-file-4-ru-v1' => 'strakh',
        'fear-file-5-ru-v1' => 'strakh',
        'truth-file-lesson-docx-v1' => 'truth',
        'truth-file-lesson-pdf-v1' => 'truth',
        'truth-file-slides-v1' => 'truth',
        'truth-file-handout-docx-v1' => 'truth',
        'truth-file-handout-pdf-v1' => 'truth',
        'vineyard-file-lesson-docx-v1' => 'vineyard',
        'vineyard-file-lesson-pdf-v1' => 'vineyard',
        'vineyard-file-slides-v1' => 'vineyard',
        'vineyard-file-handout-docx-v1' => 'vineyard',
        'vineyard-file-handout-pdf-v1' => 'vineyard',
    ],
    'sets' => [
        'neighbor' => [
            0 => 'german-neighbor-notes-docx-20261003',
            1 => 'german-neighbor-notes-pdf-20261003',
            2 => 'german-neighbor-presentation-pptx-20261003',
        ],
        'words' => [
            0 => 'german-words-notes-docx-20261003',
            1 => 'german-words-notes-pdf-20261003',
            2 => 'german-words-worksheet-docx-20261003',
            3 => 'german-words-worksheet-pdf-20261003',
            4 => 'german-words-presentation-pptx-20261003',
        ],
        'zakkhei' => [
            0 => 'german-zakkhei-notes-docx-20261003',
            1 => 'german-zakkhei-notes-pdf-20261003',
            2 => 'german-zakkhei-worksheet-docx-20261003',
            3 => 'german-zakkhei-worksheet-pdf-20261003',
            4 => 'german-zakkhei-presentation-pptx-20261003',
        ],
        'judge' => [
            0 => 'german-judge-notes-docx-20261003',
            1 => 'german-judge-notes-pdf-20261003',
            2 => 'german-judge-worksheet-docx-20261003',
            3 => 'german-judge-worksheet-pdf-20261003',
            4 => 'german-judge-presentation-pptx-20261003',
        ],
        'sheep' => [
            0 => 'german-sheep-notes-docx-20261003',
            1 => 'german-sheep-notes-pdf-20261003',
            2 => 'german-sheep-worksheet-docx-20261003',
            3 => 'german-sheep-worksheet-pdf-20261003',
            4 => 'german-sheep-presentation-pptx-20261003',
        ],
        'talent' => [
            0 => 'german-talent-notes-docx-20261003',
            1 => 'german-talent-notes-pdf-20261003',
            2 => 'german-talent-worksheet-docx-20261003',
            3 => 'german-talent-worksheet-pdf-20261003',
            4 => 'german-talent-presentation-pptx-20261003',
        ],
        'anger' => [
            0 => 'german-anger-notes-docx-20261003',
            1 => 'german-anger-notes-pdf-20261003',
            2 => 'german-anger-worksheet-docx-20261003',
            3 => 'german-anger-worksheet-pdf-20261003',
            4 => 'german-anger-presentation-pptx-20261003',
        ],
        'choices' => [
            0 => 'german-choices-notes-docx-20261003',
            1 => 'german-choices-notes-pdf-20261003',
            2 => 'german-choices-worksheet-docx-20261003',
            3 => 'german-choices-worksheet-pdf-20261003',
            4 => 'german-choices-presentation-pptx-20261003',
        ],
        'envy' => [
            0 => 'german-envy-notes-docx-20261003',
            1 => 'german-envy-notes-pdf-20261003',
            2 => 'german-envy-worksheet-docx-20261003',
            3 => 'german-envy-worksheet-pdf-20261003',
            4 => 'german-envy-presentation-pptx-20261003',
        ],
        'forgiveness' => [
            0 => 'german-forgiveness-notes-docx-20261003',
            1 => 'german-forgiveness-notes-pdf-20261003',
            2 => 'german-forgiveness-worksheet-docx-20261003',
            3 => 'german-forgiveness-worksheet-pdf-20261003',
            4 => 'german-forgiveness-presentation-pptx-20261003',
        ],
        'friends' => [
            0 => 'german-friends-notes-docx-20261003',
            1 => 'german-friends-notes-pdf-20261003',
            2 => 'german-friends-worksheet-docx-20261003',
            3 => 'german-friends-worksheet-pdf-20261003',
            4 => 'german-friends-presentation-pptx-20261003',
        ],
        'joseph' => [
            0 => 'german-joseph-notes-docx-20261003',
            1 => 'german-joseph-notes-pdf-20261003',
            2 => 'german-joseph-worksheet-docx-20261003',
            3 => 'german-joseph-worksheet-pdf-20261003',
            4 => 'german-joseph-presentation-pptx-20261003',
        ],
        'peter' => [
            0 => 'german-peter-notes-docx-20261003',
            1 => 'german-peter-notes-pdf-20261003',
            2 => 'german-peter-worksheet-docx-20261003',
            3 => 'german-peter-worksheet-pdf-20261003',
            4 => 'german-peter-presentation-pptx-20261003',
        ],
        'pressure' => [
            0 => 'german-pressure-notes-docx-20261003',
            1 => 'german-pressure-notes-pdf-20261003',
            2 => 'german-pressure-worksheet-docx-20261003',
            3 => 'german-pressure-worksheet-pdf-20261003',
            4 => 'german-pressure-presentation-pptx-20261003',
        ],
        'spasibo' => [
            0 => 'german-spasibo-notes-docx-20261003',
            1 => 'german-spasibo-notes-pdf-20261003',
            2 => 'german-spasibo-worksheet-docx-20261003',
            3 => 'german-spasibo-worksheet-pdf-20261003',
            4 => 'german-spasibo-presentation-pptx-20261003',
        ],
        'strakh' => [
            0 => 'german-strakh-notes-docx-20261003',
            1 => 'german-strakh-notes-pdf-20261003',
            2 => 'german-strakh-worksheet-docx-20261003',
            3 => 'german-strakh-worksheet-pdf-20261003',
            4 => 'german-strakh-presentation-pptx-20261003',
        ],
        'truth' => [
            0 => 'german-truth-notes-docx-20261003',
            1 => 'german-truth-notes-pdf-20261003',
            2 => 'german-truth-worksheet-docx-20261003',
            3 => 'german-truth-worksheet-pdf-20261003',
            4 => 'german-truth-presentation-pptx-20261003',
        ],
        'vineyard' => [
            0 => 'german-vineyard-notes-docx-20261003',
            1 => 'german-vineyard-notes-pdf-20261003',
            2 => 'german-vineyard-worksheet-docx-20261003',
            3 => 'german-vineyard-worksheet-pdf-20261003',
            4 => 'german-vineyard-presentation-pptx-20261003',
        ],
    ],
    'files' => [
        'german-neighbor-notes-docx-20261003' => [
            'path' => 'assets/lessons/kto-moi-blizhnii/de/Unterrichtsplan.docx',
            'sha256' => '98348c87f8a9dd3b8dc16bf91ce795ba1be8d276d0d947023c63cdfc0cd70fc8',
            'downloadName' => 'kto-moi-blizhnii-Unterrichtsplan.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-neighbor-notes-pdf-20261003' => [
            'path' => 'assets/lessons/kto-moi-blizhnii/de/Unterrichtsplan.pdf',
            'sha256' => '5a7a74a94d48553cd9177eef7982d08c6500ab28d85652071b164cd3933a11e5',
            'downloadName' => 'kto-moi-blizhnii-Unterrichtsplan.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_pdf',
            'mime' => 'application/pdf',
        ],
        'german-neighbor-presentation-pptx-20261003' => [
            'path' => 'assets/lessons/kto-moi-blizhnii/de/Präsentation.pptx',
            'sha256' => '70bcb316d8b11c739d4e9cffaf1be08349480d42cbb3b887b28d4d3c9f8310a6',
            'downloadName' => 'kto-moi-blizhnii-Präsentation.pptx',
            'locale' => 'de',
            'kind' => 'presentation',
            'catalogFormat' => 'presentation',
            'labelKey' => 'documentation_german_presentation_pptx',
            'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        ],
        'german-words-notes-docx-20261003' => [
            'path' => 'assets/lessons/slova-ranyat-slova-lechat/de/Unterrichtsplan.docx',
            'sha256' => 'bce69aae340b4f5c0dd7398571e11315d564d3e9d3744a2e64347ea128197b8d',
            'downloadName' => 'slova-ranyat-slova-lechat-Unterrichtsplan.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-words-notes-pdf-20261003' => [
            'path' => 'assets/lessons/slova-ranyat-slova-lechat/de/Unterrichtsplan.pdf',
            'sha256' => 'e438db5158282922668d4c636197f1805d81a3ed2718e892c0e7ee19f95eb293',
            'downloadName' => 'slova-ranyat-slova-lechat-Unterrichtsplan.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_pdf',
            'mime' => 'application/pdf',
        ],
        'german-words-worksheet-docx-20261003' => [
            'path' => 'assets/lessons/slova-ranyat-slova-lechat/de/Arbeitsmaterial.docx',
            'sha256' => '99fcb1813304b9185e27d9aa5983aba12800af20b28a89fc3d55066be569d405',
            'downloadName' => 'slova-ranyat-slova-lechat-Arbeitsmaterial.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-words-worksheet-pdf-20261003' => [
            'path' => 'assets/lessons/slova-ranyat-slova-lechat/de/Arbeitsmaterial.pdf',
            'sha256' => 'b32f1ae0ad3b30c8e9327676501b0ffc14876bb5a47b9028a683acaba0b76564',
            'downloadName' => 'slova-ranyat-slova-lechat-Arbeitsmaterial.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_pdf',
            'mime' => 'application/pdf',
        ],
        'german-words-presentation-pptx-20261003' => [
            'path' => 'assets/lessons/slova-ranyat-slova-lechat/de/Präsentation.pptx',
            'sha256' => '646da6249bbb8c0185795584c6e54a69f379fb69e2f1aa6a1def393935d28ffb',
            'downloadName' => 'slova-ranyat-slova-lechat-Präsentation.pptx',
            'locale' => 'de',
            'kind' => 'presentation',
            'catalogFormat' => 'presentation',
            'labelKey' => 'documentation_german_presentation_pptx',
            'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        ],
        'german-zakkhei-notes-docx-20261003' => [
            'path' => 'assets/lessons/zakkhei/de/Unterrichtsplan.docx',
            'sha256' => '64b740ab09aaf06b2c1bd6877584153e144644881cab8f86d8f263a91b165222',
            'downloadName' => 'zakkhei-Unterrichtsplan.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-zakkhei-notes-pdf-20261003' => [
            'path' => 'assets/lessons/zakkhei/de/Unterrichtsplan.pdf',
            'sha256' => 'cb67501b1d590a4d2fbd72b4fdff1d45c3689f15f0d95949cde70c47fe17a6d4',
            'downloadName' => 'zakkhei-Unterrichtsplan.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_pdf',
            'mime' => 'application/pdf',
        ],
        'german-zakkhei-worksheet-docx-20261003' => [
            'path' => 'assets/lessons/zakkhei/de/Arbeitsmaterial.docx',
            'sha256' => '5517f2816564c001d17186a2b81525f50ab1582f98ecdd7421e2a7cbc8cb007c',
            'downloadName' => 'zakkhei-Arbeitsmaterial.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-zakkhei-worksheet-pdf-20261003' => [
            'path' => 'assets/lessons/zakkhei/de/Arbeitsmaterial.pdf',
            'sha256' => 'b9627e34ba3c34badf038591a1d1806dc5c9155e733248624a1f5adeeb7ab022',
            'downloadName' => 'zakkhei-Arbeitsmaterial.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_pdf',
            'mime' => 'application/pdf',
        ],
        'german-zakkhei-presentation-pptx-20261003' => [
            'path' => 'assets/lessons/zakkhei/de/Präsentation.pptx',
            'sha256' => '1fdf0373867bbb373ae05ecafefa42980792ab82805b6b1740c1765ad84fa886',
            'downloadName' => 'zakkhei-Präsentation.pptx',
            'locale' => 'de',
            'kind' => 'presentation',
            'catalogFormat' => 'presentation',
            'labelKey' => 'documentation_german_presentation_pptx',
            'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        ],
        'german-judge-notes-docx-20261003' => [
            'path' => 'assets/lessons/ne-speshi-sudit/de/Unterrichtsplan.docx',
            'sha256' => '9b64125ae74f8b9a4371f5c258bee493f60142852ab42062d6eaafe688c65300',
            'downloadName' => 'ne-speshi-sudit-Unterrichtsplan.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-judge-notes-pdf-20261003' => [
            'path' => 'assets/lessons/ne-speshi-sudit/de/Unterrichtsplan.pdf',
            'sha256' => 'f1be73bb9db62aa94f897dddbf16470a159144c1011957afc5f6abbce823a6ed',
            'downloadName' => 'ne-speshi-sudit-Unterrichtsplan.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_pdf',
            'mime' => 'application/pdf',
        ],
        'german-judge-worksheet-docx-20261003' => [
            'path' => 'assets/lessons/ne-speshi-sudit/de/Arbeitsmaterial.docx',
            'sha256' => '5a4199568ae5c2962696f25a6a6034cd33426de3723c19f2574920bc9ffc23eb',
            'downloadName' => 'ne-speshi-sudit-Arbeitsmaterial.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-judge-worksheet-pdf-20261003' => [
            'path' => 'assets/lessons/ne-speshi-sudit/de/Arbeitsmaterial.pdf',
            'sha256' => '3752c10e4d633c8824bcc9f2eb02f3746f169276e5bc817e29d29febfaa8dd8a',
            'downloadName' => 'ne-speshi-sudit-Arbeitsmaterial.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_pdf',
            'mime' => 'application/pdf',
        ],
        'german-judge-presentation-pptx-20261003' => [
            'path' => 'assets/lessons/ne-speshi-sudit/de/Präsentation.pptx',
            'sha256' => 'da9b37021a500bc7d4c3011140ae3de496c1624a97d8314b5297e9ee7c19cacc',
            'downloadName' => 'ne-speshi-sudit-Präsentation.pptx',
            'locale' => 'de',
            'kind' => 'presentation',
            'catalogFormat' => 'presentation',
            'labelKey' => 'documentation_german_presentation_pptx',
            'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        ],
        'german-sheep-notes-docx-20261003' => [
            'path' => 'assets/lessons/poteryannaya-ovechka/de/Unterrichtsplan.docx',
            'sha256' => '3553fdf2e31e0a5bdfdca027f64f1a1bc98185e5cd95ad4c7aa55721ac0182cd',
            'downloadName' => 'poteryannaya-ovechka-Unterrichtsplan.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-sheep-notes-pdf-20261003' => [
            'path' => 'assets/lessons/poteryannaya-ovechka/de/Unterrichtsplan.pdf',
            'sha256' => 'cc6373015a111f476ca08ee3b0e4a313c3c3a90d81ee02870a89da7e61bb31d2',
            'downloadName' => 'poteryannaya-ovechka-Unterrichtsplan.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_pdf',
            'mime' => 'application/pdf',
        ],
        'german-sheep-worksheet-docx-20261003' => [
            'path' => 'assets/lessons/poteryannaya-ovechka/de/Arbeitsmaterial.docx',
            'sha256' => 'f0de5245aaaaee8e8c2ab2631657d80ff833180e7486ae4fec7141db8ad80b81',
            'downloadName' => 'poteryannaya-ovechka-Arbeitsmaterial.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-sheep-worksheet-pdf-20261003' => [
            'path' => 'assets/lessons/poteryannaya-ovechka/de/Arbeitsmaterial.pdf',
            'sha256' => '0818ca89d226ba660f99400684faba8725e63ab91744e1fe2ae387f36b90583b',
            'downloadName' => 'poteryannaya-ovechka-Arbeitsmaterial.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_pdf',
            'mime' => 'application/pdf',
        ],
        'german-sheep-presentation-pptx-20261003' => [
            'path' => 'assets/lessons/poteryannaya-ovechka/de/Präsentation.pptx',
            'sha256' => '43a6eaf9e68e12f6416ddee2c0c9167e062b8cee099a0ef81e21f9011fba14fd',
            'downloadName' => 'poteryannaya-ovechka-Präsentation.pptx',
            'locale' => 'de',
            'kind' => 'presentation',
            'catalogFormat' => 'presentation',
            'labelKey' => 'documentation_german_presentation_pptx',
            'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        ],
        'german-talent-notes-docx-20261003' => [
            'path' => 'assets/lessons/chto-delat-so-svoim-talantom/de/Unterrichtsplan.docx',
            'sha256' => 'df09880b4836c722706b6c42dbf424f08dfe59e2b43d2a416128598cb04a34d8',
            'downloadName' => 'chto-delat-so-svoim-talantom-Unterrichtsplan.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-talent-notes-pdf-20261003' => [
            'path' => 'assets/lessons/chto-delat-so-svoim-talantom/de/Unterrichtsplan.pdf',
            'sha256' => '9cb272195219fb48b9e59c623e421cb63c625c6b53da08783819bde90c89d2f2',
            'downloadName' => 'chto-delat-so-svoim-talantom-Unterrichtsplan.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_pdf',
            'mime' => 'application/pdf',
        ],
        'german-talent-worksheet-docx-20261003' => [
            'path' => 'assets/lessons/chto-delat-so-svoim-talantom/de/Arbeitsmaterial.docx',
            'sha256' => '527c684a68aa6151a04b24022607114a07f6381e5f22caec256a7c709ee44040',
            'downloadName' => 'chto-delat-so-svoim-talantom-Arbeitsmaterial.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-talent-worksheet-pdf-20261003' => [
            'path' => 'assets/lessons/chto-delat-so-svoim-talantom/de/Arbeitsmaterial.pdf',
            'sha256' => '52aa999a6db67f4bb5f58db29ce9a20bf6db9bbc0a02fedc1ffc22513e27b555',
            'downloadName' => 'chto-delat-so-svoim-talantom-Arbeitsmaterial.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_pdf',
            'mime' => 'application/pdf',
        ],
        'german-talent-presentation-pptx-20261003' => [
            'path' => 'assets/lessons/chto-delat-so-svoim-talantom/de/Präsentation.pptx',
            'sha256' => 'e07ac9ec1b855b0398e937292606bde9da4306ddf3bd9e5abd1c39cba47550fb',
            'downloadName' => 'chto-delat-so-svoim-talantom-Präsentation.pptx',
            'locale' => 'de',
            'kind' => 'presentation',
            'catalogFormat' => 'presentation',
            'labelKey' => 'documentation_german_presentation_pptx',
            'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        ],
        'german-anger-notes-docx-20261003' => [
            'path' => 'assets/lessons/ya-razozlilsya-chto-teper/de/Unterrichtsplan.docx',
            'sha256' => '36d24235ca8b7176ce568980305351ba287d903b30863bd0b9169905fde59924',
            'downloadName' => 'ya-razozlilsya-chto-teper-Unterrichtsplan.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-anger-notes-pdf-20261003' => [
            'path' => 'assets/lessons/ya-razozlilsya-chto-teper/de/Unterrichtsplan.pdf',
            'sha256' => 'd6b909024d1193b8eb735dfb63422274efc05813d24f7cadad5d8dfd932cdd2e',
            'downloadName' => 'ya-razozlilsya-chto-teper-Unterrichtsplan.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_pdf',
            'mime' => 'application/pdf',
        ],
        'german-anger-worksheet-docx-20261003' => [
            'path' => 'assets/lessons/ya-razozlilsya-chto-teper/de/Arbeitsmaterial.docx',
            'sha256' => '0042cea862c7ca022442d8f42a95bd96b2a62c1cd15a26b8293bbdb77c902832',
            'downloadName' => 'ya-razozlilsya-chto-teper-Arbeitsmaterial.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-anger-worksheet-pdf-20261003' => [
            'path' => 'assets/lessons/ya-razozlilsya-chto-teper/de/Arbeitsmaterial.pdf',
            'sha256' => 'e2e4fe7d0e001ae566bc71cccf9a2e82c022cb4158abd894f9b8bef216c37876',
            'downloadName' => 'ya-razozlilsya-chto-teper-Arbeitsmaterial.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_pdf',
            'mime' => 'application/pdf',
        ],
        'german-anger-presentation-pptx-20261003' => [
            'path' => 'assets/lessons/ya-razozlilsya-chto-teper/de/Präsentation.pptx',
            'sha256' => 'c16904b3206023544714442dcefc608667d46179995d76300026bb2b247912bd',
            'downloadName' => 'ya-razozlilsya-chto-teper-Präsentation.pptx',
            'locale' => 'de',
            'kind' => 'presentation',
            'catalogFormat' => 'presentation',
            'labelKey' => 'documentation_german_presentation_pptx',
            'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        ],
        'german-choices-notes-docx-20261003' => [
            'path' => 'assets/lessons/ya-imeyu-pravo-vybirat/de/Unterrichtsplan.docx',
            'sha256' => 'dfece04aaf3ec838968a91dc561740f620978f3e74f58a5e11aa7347ea0ab6fc',
            'downloadName' => 'ya-imeyu-pravo-vybirat-Unterrichtsplan.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-choices-notes-pdf-20261003' => [
            'path' => 'assets/lessons/ya-imeyu-pravo-vybirat/de/Unterrichtsplan.pdf',
            'sha256' => '011f673b82c4be00cfc1d80e9272cb6e0c06a90e40e081026da885b6f7c3a31f',
            'downloadName' => 'ya-imeyu-pravo-vybirat-Unterrichtsplan.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_pdf',
            'mime' => 'application/pdf',
        ],
        'german-choices-worksheet-docx-20261003' => [
            'path' => 'assets/lessons/ya-imeyu-pravo-vybirat/de/Arbeitsmaterial.docx',
            'sha256' => 'a301acfa2b178d9792dff86c95066aaba88b726aa94d4b661321c54872ad5ac5',
            'downloadName' => 'ya-imeyu-pravo-vybirat-Arbeitsmaterial.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-choices-worksheet-pdf-20261003' => [
            'path' => 'assets/lessons/ya-imeyu-pravo-vybirat/de/Arbeitsmaterial.pdf',
            'sha256' => '948aa2a9b6356973ec2ed3baea18250d74d533a00cdcc2b2fb078ccb18115052',
            'downloadName' => 'ya-imeyu-pravo-vybirat-Arbeitsmaterial.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_pdf',
            'mime' => 'application/pdf',
        ],
        'german-choices-presentation-pptx-20261003' => [
            'path' => 'assets/lessons/ya-imeyu-pravo-vybirat/de/Präsentation.pptx',
            'sha256' => 'cf0c2132c29b79332e6880320851ba6a7edd56b71d4884fabe4cf0b139ad1213',
            'downloadName' => 'ya-imeyu-pravo-vybirat-Präsentation.pptx',
            'locale' => 'de',
            'kind' => 'presentation',
            'catalogFormat' => 'presentation',
            'labelKey' => 'documentation_german_presentation_pptx',
            'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        ],
        'german-envy-notes-docx-20261003' => [
            'path' => 'assets/lessons/a-esli-mne-zavidno/de/Unterrichtsplan.docx',
            'sha256' => 'c294983d4abc4442fea5e6f95d14bfc633bec71aa9bab4c2797d4f0854274052',
            'downloadName' => 'a-esli-mne-zavidno-Unterrichtsplan.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-envy-notes-pdf-20261003' => [
            'path' => 'assets/lessons/a-esli-mne-zavidno/de/Unterrichtsplan.pdf',
            'sha256' => '07fba4224e79ba1edb5a2512d3526266e02155983344277c256eeeaa47a76a39',
            'downloadName' => 'a-esli-mne-zavidno-Unterrichtsplan.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_pdf',
            'mime' => 'application/pdf',
        ],
        'german-envy-worksheet-docx-20261003' => [
            'path' => 'assets/lessons/a-esli-mne-zavidno/de/Arbeitsmaterial.docx',
            'sha256' => '57564e6aedc508344a9794e78494782359a381f60096d90bdfaa42f366cf847d',
            'downloadName' => 'a-esli-mne-zavidno-Arbeitsmaterial.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-envy-worksheet-pdf-20261003' => [
            'path' => 'assets/lessons/a-esli-mne-zavidno/de/Arbeitsmaterial.pdf',
            'sha256' => '1f7bb420690ddbdbbc5285fe95b8da74d071e1f2cf778f1e9fe4928ce77e3ba6',
            'downloadName' => 'a-esli-mne-zavidno-Arbeitsmaterial.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_pdf',
            'mime' => 'application/pdf',
        ],
        'german-envy-presentation-pptx-20261003' => [
            'path' => 'assets/lessons/a-esli-mne-zavidno/de/Präsentation.pptx',
            'sha256' => '92654808db5e58353f84e18a26544379725bf8951bd2b57691379f49324cdc07',
            'downloadName' => 'a-esli-mne-zavidno-Präsentation.pptx',
            'locale' => 'de',
            'kind' => 'presentation',
            'catalogFormat' => 'presentation',
            'labelKey' => 'documentation_german_presentation_pptx',
            'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        ],
        'german-forgiveness-notes-docx-20261003' => [
            'path' => 'assets/lessons/ya-ne-hochu-proshchat/de/Unterrichtsplan.docx',
            'sha256' => 'be3390dd656843779254d819318afefe1318499bf49932933170e8ef2597fbd9',
            'downloadName' => 'ya-ne-hochu-proshchat-Unterrichtsplan.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-forgiveness-notes-pdf-20261003' => [
            'path' => 'assets/lessons/ya-ne-hochu-proshchat/de/Unterrichtsplan.pdf',
            'sha256' => '1c6ef00c7028b5506ae97b1804492f3d2c747c829dd8ceaf72904dc2a257884e',
            'downloadName' => 'ya-ne-hochu-proshchat-Unterrichtsplan.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_pdf',
            'mime' => 'application/pdf',
        ],
        'german-forgiveness-worksheet-docx-20261003' => [
            'path' => 'assets/lessons/ya-ne-hochu-proshchat/de/Arbeitsmaterial.docx',
            'sha256' => '4dac181fb8840a96b7754a49d974f47b900d790c39d1b882fb52a37bfedfe37d',
            'downloadName' => 'ya-ne-hochu-proshchat-Arbeitsmaterial.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-forgiveness-worksheet-pdf-20261003' => [
            'path' => 'assets/lessons/ya-ne-hochu-proshchat/de/Arbeitsmaterial.pdf',
            'sha256' => '1b1a5adf75601c91c58894338bf90e773bd0cc1ea29405734dd3c1d246a0f046',
            'downloadName' => 'ya-ne-hochu-proshchat-Arbeitsmaterial.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_pdf',
            'mime' => 'application/pdf',
        ],
        'german-forgiveness-presentation-pptx-20261003' => [
            'path' => 'assets/lessons/ya-ne-hochu-proshchat/de/Präsentation.pptx',
            'sha256' => 'fb4da7778545bc5b6e93190aa2f5cc97b071714572b49e6242fa1ea541cc0ed1',
            'downloadName' => 'ya-ne-hochu-proshchat-Präsentation.pptx',
            'locale' => 'de',
            'kind' => 'presentation',
            'catalogFormat' => 'presentation',
            'labelKey' => 'documentation_german_presentation_pptx',
            'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        ],
        'german-friends-notes-docx-20261003' => [
            'path' => 'assets/lessons/chetvero-druzey/de/Unterrichtsplan.docx',
            'sha256' => '2a7bf439468486d0fd40919bdf8f49dde314d63715a8993654ec0c051c6ec17c',
            'downloadName' => 'chetvero-druzey-Unterrichtsplan.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-friends-notes-pdf-20261003' => [
            'path' => 'assets/lessons/chetvero-druzey/de/Unterrichtsplan.pdf',
            'sha256' => '1b1067fdb78db9303604c15014770e7210b73bf8b46fc9ea3c4cd510b7524d2a',
            'downloadName' => 'chetvero-druzey-Unterrichtsplan.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_pdf',
            'mime' => 'application/pdf',
        ],
        'german-friends-worksheet-docx-20261003' => [
            'path' => 'assets/lessons/chetvero-druzey/de/Arbeitsmaterial.docx',
            'sha256' => '4029e62c37a6fbbbd0cc7200faeb1cc7d82f51af5253d42768e5253937f18e71',
            'downloadName' => 'chetvero-druzey-Arbeitsmaterial.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-friends-worksheet-pdf-20261003' => [
            'path' => 'assets/lessons/chetvero-druzey/de/Arbeitsmaterial.pdf',
            'sha256' => '45e0d7353cd790b7e1513e5b44a6cfd004536f57ac8e4521a502223ec2f30349',
            'downloadName' => 'chetvero-druzey-Arbeitsmaterial.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_pdf',
            'mime' => 'application/pdf',
        ],
        'german-friends-presentation-pptx-20261003' => [
            'path' => 'assets/lessons/chetvero-druzey/de/Präsentation.pptx',
            'sha256' => '5e279b6c57cbc504b956ddc35881983de8921cbc261450afb88609e1dd3ba28c',
            'downloadName' => 'chetvero-druzey-Präsentation.pptx',
            'locale' => 'de',
            'kind' => 'presentation',
            'catalogFormat' => 'presentation',
            'labelKey' => 'documentation_german_presentation_pptx',
            'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        ],
        'german-joseph-notes-docx-20261003' => [
            'path' => 'assets/lessons/kogda-nikto-ne-vidit/de/Unterrichtsplan.docx',
            'sha256' => '7260a24284e1bdf3a50a0861920464b6c0160340ba6e6ee144247124a3f83796',
            'downloadName' => 'kogda-nikto-ne-vidit-Unterrichtsplan.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-joseph-notes-pdf-20261003' => [
            'path' => 'assets/lessons/kogda-nikto-ne-vidit/de/Unterrichtsplan.pdf',
            'sha256' => '3da6ad756925754bccc21f8aa155a0b9fbed7eb8e8e4a923661d6b50d68a1713',
            'downloadName' => 'kogda-nikto-ne-vidit-Unterrichtsplan.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_pdf',
            'mime' => 'application/pdf',
        ],
        'german-joseph-worksheet-docx-20261003' => [
            'path' => 'assets/lessons/kogda-nikto-ne-vidit/de/Arbeitsmaterial.docx',
            'sha256' => 'bea11f9ae2dbb57738a2c5a53a5f1e0b2c6e09fd3d989511e955624a282521ca',
            'downloadName' => 'kogda-nikto-ne-vidit-Arbeitsmaterial.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-joseph-worksheet-pdf-20261003' => [
            'path' => 'assets/lessons/kogda-nikto-ne-vidit/de/Arbeitsmaterial.pdf',
            'sha256' => 'e3635e0e0c462de3078d43865992f4eef87db8c409b0b802bde21d2556046a8a',
            'downloadName' => 'kogda-nikto-ne-vidit-Arbeitsmaterial.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_pdf',
            'mime' => 'application/pdf',
        ],
        'german-joseph-presentation-pptx-20261003' => [
            'path' => 'assets/lessons/kogda-nikto-ne-vidit/de/Präsentation.pptx',
            'sha256' => '6af6928ef7c952384ec9388e051f71036f5e1d88130d9d645379a10a96f052b3',
            'downloadName' => 'kogda-nikto-ne-vidit-Präsentation.pptx',
            'locale' => 'de',
            'kind' => 'presentation',
            'catalogFormat' => 'presentation',
            'labelKey' => 'documentation_german_presentation_pptx',
            'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        ],
        'german-peter-notes-docx-20261003' => [
            'path' => 'assets/lessons/ya-oshibsya-vse-poteryano/de/Unterrichtsplan.docx',
            'sha256' => 'aa2e16e5573bce88fec61b4e47d960fc3052dbe54df58c088092bd4b8365c6b6',
            'downloadName' => 'ya-oshibsya-vse-poteryano-Unterrichtsplan.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-peter-notes-pdf-20261003' => [
            'path' => 'assets/lessons/ya-oshibsya-vse-poteryano/de/Unterrichtsplan.pdf',
            'sha256' => 'da6eb12e2606f1b1c176e6b7cce1263ff5ecb5ce9c118409bf1c473d63171a26',
            'downloadName' => 'ya-oshibsya-vse-poteryano-Unterrichtsplan.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_pdf',
            'mime' => 'application/pdf',
        ],
        'german-peter-worksheet-docx-20261003' => [
            'path' => 'assets/lessons/ya-oshibsya-vse-poteryano/de/Arbeitsmaterial.docx',
            'sha256' => 'db5700b9ff92d65ea07b7e72f9732e750d009d2282c944b136449fdc14d6edfb',
            'downloadName' => 'ya-oshibsya-vse-poteryano-Arbeitsmaterial.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-peter-worksheet-pdf-20261003' => [
            'path' => 'assets/lessons/ya-oshibsya-vse-poteryano/de/Arbeitsmaterial.pdf',
            'sha256' => 'e5ec87911005aac9215132a9aae40840b73fe930b1eb99f279424bbf9124eda4',
            'downloadName' => 'ya-oshibsya-vse-poteryano-Arbeitsmaterial.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_pdf',
            'mime' => 'application/pdf',
        ],
        'german-peter-presentation-pptx-20261003' => [
            'path' => 'assets/lessons/ya-oshibsya-vse-poteryano/de/Präsentation.pptx',
            'sha256' => '827e2c3959e2271f7ad14315f1e821ae5ff8f9973a412567cbdc9bdf84e2cd61',
            'downloadName' => 'ya-oshibsya-vse-poteryano-Präsentation.pptx',
            'locale' => 'de',
            'kind' => 'presentation',
            'catalogFormat' => 'presentation',
            'labelKey' => 'documentation_german_presentation_pptx',
            'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        ],
        'german-pressure-notes-docx-20261003' => [
            'path' => 'assets/lessons/vse-tak-delayut/de/Unterrichtsplan.docx',
            'sha256' => '630a3962eb8d49d691e1465fc89d665b22cde4d231d368bda83a2f3e7a0faee5',
            'downloadName' => 'vse-tak-delayut-Unterrichtsplan.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-pressure-notes-pdf-20261003' => [
            'path' => 'assets/lessons/vse-tak-delayut/de/Unterrichtsplan.pdf',
            'sha256' => 'e9615e2dd2de9cb66b9571edb6e3697498ef75dd4b264666d29de1fb2b76fccd',
            'downloadName' => 'vse-tak-delayut-Unterrichtsplan.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_pdf',
            'mime' => 'application/pdf',
        ],
        'german-pressure-worksheet-docx-20261003' => [
            'path' => 'assets/lessons/vse-tak-delayut/de/Arbeitsmaterial.docx',
            'sha256' => '0927549a5c48c5aec111947853ed132f05feea57a67e558c74b97ff9645641d2',
            'downloadName' => 'vse-tak-delayut-Arbeitsmaterial.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-pressure-worksheet-pdf-20261003' => [
            'path' => 'assets/lessons/vse-tak-delayut/de/Arbeitsmaterial.pdf',
            'sha256' => 'fe731f8a01bc39216b49f7cf3aee8d6d87d449dd7cb2a626d1bdb06dd8d56dc9',
            'downloadName' => 'vse-tak-delayut-Arbeitsmaterial.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_pdf',
            'mime' => 'application/pdf',
        ],
        'german-pressure-presentation-pptx-20261003' => [
            'path' => 'assets/lessons/vse-tak-delayut/de/Präsentation.pptx',
            'sha256' => '959fab5b68fcc3434683e97ea291156ac3330d2a92152e6b0e64a3b3d9c29058',
            'downloadName' => 'vse-tak-delayut-Präsentation.pptx',
            'locale' => 'de',
            'kind' => 'presentation',
            'catalogFormat' => 'presentation',
            'labelKey' => 'documentation_german_presentation_pptx',
            'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        ],
        'german-spasibo-notes-docx-20261003' => [
            'path' => 'assets/lessons/spasibo-pochemu-zabyvaem-dobro/de/Unterrichtsplan.docx',
            'sha256' => 'ffc844edbc564dc94fbe00656d77414f72d5ce3f4a3863a8250da66140275971',
            'downloadName' => 'spasibo-pochemu-zabyvaem-dobro-Unterrichtsplan.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-spasibo-notes-pdf-20261003' => [
            'path' => 'assets/lessons/spasibo-pochemu-zabyvaem-dobro/de/Unterrichtsplan.pdf',
            'sha256' => '935e9ae038f52afa39fb603057769aeba9ccf9ce2386e82f590562eaabcf2de5',
            'downloadName' => 'spasibo-pochemu-zabyvaem-dobro-Unterrichtsplan.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_pdf',
            'mime' => 'application/pdf',
        ],
        'german-spasibo-worksheet-docx-20261003' => [
            'path' => 'assets/lessons/spasibo-pochemu-zabyvaem-dobro/de/Arbeitsmaterial.docx',
            'sha256' => 'bdb559aba19f27179a9af3264824df269507b475bc4ed6332a3058b826ca7d95',
            'downloadName' => 'spasibo-pochemu-zabyvaem-dobro-Arbeitsmaterial.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-spasibo-worksheet-pdf-20261003' => [
            'path' => 'assets/lessons/spasibo-pochemu-zabyvaem-dobro/de/Arbeitsmaterial.pdf',
            'sha256' => '4126752cd796dea2ba20a0ec0900da8a3b1f1e2ac4868656c43fac3fe49f6eac',
            'downloadName' => 'spasibo-pochemu-zabyvaem-dobro-Arbeitsmaterial.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_pdf',
            'mime' => 'application/pdf',
        ],
        'german-spasibo-presentation-pptx-20261003' => [
            'path' => 'assets/lessons/spasibo-pochemu-zabyvaem-dobro/de/Präsentation.pptx',
            'sha256' => '6d5e0a66e751496e00ed8c79d093bd6be9707ae65f6965402c2f89ed5521d0ff',
            'downloadName' => 'spasibo-pochemu-zabyvaem-dobro-Präsentation.pptx',
            'locale' => 'de',
            'kind' => 'presentation',
            'catalogFormat' => 'presentation',
            'labelKey' => 'documentation_german_presentation_pptx',
            'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        ],
        'german-strakh-notes-docx-20261003' => [
            'path' => 'assets/lessons/kogda-mne-strashno/de/Unterrichtsplan.docx',
            'sha256' => 'd5d3fcf0f3220c669ed25a2fc1f8c91aed1759ab654830c6e631b18eeda223b6',
            'downloadName' => 'kogda-mne-strashno-Unterrichtsplan.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-strakh-notes-pdf-20261003' => [
            'path' => 'assets/lessons/kogda-mne-strashno/de/Unterrichtsplan.pdf',
            'sha256' => '8649e3de97a6a24011100ba46ffb77a3dd3255755cd9ea134a1bbffb073f966a',
            'downloadName' => 'kogda-mne-strashno-Unterrichtsplan.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_pdf',
            'mime' => 'application/pdf',
        ],
        'german-strakh-worksheet-docx-20261003' => [
            'path' => 'assets/lessons/kogda-mne-strashno/de/Arbeitsmaterial.docx',
            'sha256' => '32e77045160d063302e3d67def109786bd91a732cc39382f1ad99d85caf4b9a3',
            'downloadName' => 'kogda-mne-strashno-Arbeitsmaterial.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-strakh-worksheet-pdf-20261003' => [
            'path' => 'assets/lessons/kogda-mne-strashno/de/Arbeitsmaterial.pdf',
            'sha256' => 'e717784ee8044f0706d807053dbf1fa63df380d0c7c673cfb4b3402c8f25b574',
            'downloadName' => 'kogda-mne-strashno-Arbeitsmaterial.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_pdf',
            'mime' => 'application/pdf',
        ],
        'german-strakh-presentation-pptx-20261003' => [
            'path' => 'assets/lessons/kogda-mne-strashno/de/Präsentation.pptx',
            'sha256' => '2995bd410976518ea9bd62c6c094551c6b90ff8372500ac1a2e93b08d72a0b7b',
            'downloadName' => 'kogda-mne-strashno-Präsentation.pptx',
            'locale' => 'de',
            'kind' => 'presentation',
            'catalogFormat' => 'presentation',
            'labelKey' => 'documentation_german_presentation_pptx',
            'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        ],
        'german-truth-notes-docx-20261003' => [
            'path' => 'assets/lessons/mozhno-li-sovrat-radi-dobra/de/Unterrichtsplan.docx',
            'sha256' => '1e52f7366299e9edf1f27b4e4ffced7ed7190dc4044a8998b87f96dba7b7faf5',
            'downloadName' => 'mozhno-li-sovrat-radi-dobra-Unterrichtsplan.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-truth-notes-pdf-20261003' => [
            'path' => 'assets/lessons/mozhno-li-sovrat-radi-dobra/de/Unterrichtsplan.pdf',
            'sha256' => 'f27014d77659aae8096d5d8084087a6e431d29eb1f397dc2af6ed41031fb3f5b',
            'downloadName' => 'mozhno-li-sovrat-radi-dobra-Unterrichtsplan.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_pdf',
            'mime' => 'application/pdf',
        ],
        'german-truth-worksheet-docx-20261003' => [
            'path' => 'assets/lessons/mozhno-li-sovrat-radi-dobra/de/Arbeitsmaterial.docx',
            'sha256' => '764d8977bc893d04e0b5b3a8aa7d3c0d55158bfd27e22605fd256e98ef9e6dad',
            'downloadName' => 'mozhno-li-sovrat-radi-dobra-Arbeitsmaterial.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-truth-worksheet-pdf-20261003' => [
            'path' => 'assets/lessons/mozhno-li-sovrat-radi-dobra/de/Arbeitsmaterial.pdf',
            'sha256' => '5dec7cc1016e0ebcd2ecdef367567e667b3726ca8b4bb1e1f6a37948ec6c1143',
            'downloadName' => 'mozhno-li-sovrat-radi-dobra-Arbeitsmaterial.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_pdf',
            'mime' => 'application/pdf',
        ],
        'german-truth-presentation-pptx-20261003' => [
            'path' => 'assets/lessons/mozhno-li-sovrat-radi-dobra/de/Präsentation.pptx',
            'sha256' => '33758296667cae2cb7d1619cedadf98e1c6b5c8a1f4ac272d94e130e6eb88a76',
            'downloadName' => 'mozhno-li-sovrat-radi-dobra-Präsentation.pptx',
            'locale' => 'de',
            'kind' => 'presentation',
            'catalogFormat' => 'presentation',
            'labelKey' => 'documentation_german_presentation_pptx',
            'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        ],
        'german-vineyard-notes-docx-20261003' => [
            'path' => 'assets/lessons/pochemu-emu-bolshe-chem-mne/de/Unterrichtsplan.docx',
            'sha256' => '72576912ab88106080d94b7d1ee2fccaf4ad7526ca908c3b0b4ca3b7196b417c',
            'downloadName' => 'pochemu-emu-bolshe-chem-mne-Unterrichtsplan.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-vineyard-notes-pdf-20261003' => [
            'path' => 'assets/lessons/pochemu-emu-bolshe-chem-mne/de/Unterrichtsplan.pdf',
            'sha256' => '8c4c465bfb5315ab13671e53ec52534ed34050cd5f0bb26ceb075d9b16875404',
            'downloadName' => 'pochemu-emu-bolshe-chem-mne-Unterrichtsplan.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'notes',
            'labelKey' => 'documentation_german_notes_pdf',
            'mime' => 'application/pdf',
        ],
        'german-vineyard-worksheet-docx-20261003' => [
            'path' => 'assets/lessons/pochemu-emu-bolshe-chem-mne/de/Arbeitsmaterial.docx',
            'sha256' => '304e3e60af97f33575e9a7e59c9b7f49c36eef341566615aece7664809a82950',
            'downloadName' => 'pochemu-emu-bolshe-chem-mne-Arbeitsmaterial.docx',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_docx',
            'mime' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        'german-vineyard-worksheet-pdf-20261003' => [
            'path' => 'assets/lessons/pochemu-emu-bolshe-chem-mne/de/Arbeitsmaterial.pdf',
            'sha256' => '32323f087ed0c9fce330855456958a4f7952775f10527e590dafe4f9e44d1c62',
            'downloadName' => 'pochemu-emu-bolshe-chem-mne-Arbeitsmaterial.pdf',
            'locale' => 'de',
            'kind' => 'plan',
            'catalogFormat' => 'worksheet',
            'labelKey' => 'documentation_german_worksheet_pdf',
            'mime' => 'application/pdf',
        ],
        'german-vineyard-presentation-pptx-20261003' => [
            'path' => 'assets/lessons/pochemu-emu-bolshe-chem-mne/de/Präsentation.pptx',
            'sha256' => '03d0f1009bdc2aa87f4f6512f158ac5b428f3ea9ce0ed9d27ad67ccf63db544f',
            'downloadName' => 'pochemu-emu-bolshe-chem-mne-Präsentation.pptx',
            'locale' => 'de',
            'kind' => 'presentation',
            'catalogFormat' => 'presentation',
            'labelKey' => 'documentation_german_presentation_pptx',
            'mime' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        ],
    ],
    'obsoleteDownloadNotice' => 'Die fünf herunterladbaren DOCX/PDF/PPTX-Dateien sind die unveränderten russischen Originale. Die deutsche Online-Anleitung enthält die übersetzten Beschriftungen und Karteninhalte.',
];
