<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { api, ApiError } from './api';
import { plainCopy, adminError, reviewPayload, type AdminCatalogEntry, type CommonTemplate, type Submission, type TaxonomyTerm, type TermKind } from './admin';
import { newBlock, projectStage } from './document';
import { emptyMetadata } from './library';
import StageRenderer from './StageRenderer.vue';
import BlockEditor from './BlockEditor.vue';
import MetadataFields from './MetadataFields.vue';
import OperationsPanel from './OperationsPanel.vue';
import type { Block, BlockType, LessonDocument, Media, MediaResponse, Messages } from './types';
import '../../css/admin.css';
const props = defineProps<{ locale: string; messages: Messages }>();
const allowed = ref(false), loading = ref(true), busy = ref(false), error = ref(''), success = ref(''), tab = ref('queue'), status = ref('pending');
const submissions = ref<Submission[]>([]), entries = ref<AdminCatalogEntry[]>([]), terms = ref<TaxonomyTerm[]>([]), templates = ref<CommonTemplate[]>([]), media = ref<Media[]>([]);
const selected = ref<Submission | null>(null), document = ref<LessonDocument | null>(null), reason = ref(''), conflict = ref(false), previewLanguage = ref(props.locale), stageIndex = ref(0);
const termId = ref(''), termRevision = ref(0), term = reactive({ kind: 'topic' as TermKind, key: '', labels: { ru: '', de: '' }, active: true });
const templateId = ref(''), templateRevision = ref(0), block = ref<Block | null>(null), blockLanguage = ref('ru'), defaultLocale = ref('ru'), attribution = ref(emptyMetadata());
const labels = reactive({ ru: { title: '', description: '' }, de: { title: '', description: '' } });
const blockType = ref<BlockType>('core.text');
const blockTypes: BlockType[] = ['core.text','core.image','core.prompt','core.single-choice','core.multiple-choice','core.poll','core.free-response','core.sequence','core.matching','core.roles','core.signals'];
const stage = computed(() => document.value?.stages[stageIndex.value]);
const projected = computed(() => stage.value && stage.value.content[previewLanguage.value] ? projectStage(stage.value, previewLanguage.value, media.value) : undefined);
async function loadTab() {
    if (!allowed.value) return;
    loading.value = true; error.value = '';
    try {
        if (tab.value === 'queue') submissions.value = (await api<{ submissions: Submission[] }>(`/api/admin/submissions${status.value ? `?status=${status.value}` : ''}`)).submissions;
        if (tab.value === 'catalog') entries.value = (await api<{ entries: AdminCatalogEntry[] }>('/api/admin/catalog')).entries;
        if (tab.value === 'taxonomy') terms.value = (await api<{ terms: TaxonomyTerm[] }>('/api/admin/taxonomy')).terms;
        if (tab.value === 'templates') templates.value = (await api<{ templates: CommonTemplate[] }>('/api/admin/templates')).templates;
    } catch (problem) { error.value = adminError(problem, props.messages); }
    finally { loading.value = false; }
}
async function initialize() {
    loading.value = true; error.value = '';
    try { const response = await api<{ admin: boolean }>('/api/admin'); allowed.value = response.admin === true; if (!allowed.value) throw new ApiError('admin_required',403); const images = await api<MediaResponse>('/api/studio/media'); media.value = images.media.filter(item => item.url.startsWith('/media/builtin/')); await loadTab(); }
    catch (problem) { allowed.value = false; error.value = adminError(problem, props.messages); }
    finally { loading.value = false; }
}
async function changeTab(value: string) { tab.value = value; selected.value = null; document.value = null; success.value = ''; await loadTab(); }
async function openSubmission(item: Submission, retainReason = false) {
    busy.value = true; error.value = '';
    try { const result = await api<{ submission: Submission; document: LessonDocument }>(`/api/admin/submissions/${item.id}`); selected.value = result.submission; document.value = result.document; stageIndex.value = 0; previewLanguage.value = result.document.locales.includes(props.locale) ? props.locale : result.document.defaultLocale; if (!retainReason) reason.value = ''; conflict.value = false; }
    catch (problem) { error.value = adminError(problem,props.messages); }
    finally { busy.value = false; }
}
async function review(decision: 'approve' | 'return') {
    if (!selected.value || busy.value || conflict.value) return;
    let body; try { body = reviewPayload(selected.value.revision, decision, reason.value); } catch { error.value = props.messages.admin_reason_required; return; }
    busy.value = true; error.value = ''; success.value = '';
    try { const result = await api<{ submission: Submission }>(`/api/admin/submissions/${selected.value.id}/review`, 'POST',body); selected.value = result.submission; success.value = props.messages.admin_saved; await loadTab(); }
    catch (problem) { error.value = adminError(problem,props.messages); conflict.value = problem instanceof ApiError && problem.status === 409; }
    finally { busy.value = false; }
}
async function visibility(kind: 'catalog' | 'templates', id: string, revision: number, visible: boolean) {
    if (busy.value) return; busy.value = true; error.value = ''; success.value = '';
    try { await api(`/api/admin/${kind}/${encodeURIComponent(id)}/visibility`, 'POST', { expectedRevision: revision, visible }); success.value = props.messages.admin_saved; await loadTab(); }
    catch (problem) { error.value = adminError(problem,props.messages); }
    finally { busy.value = false; }
}
function editTerm(item?: TaxonomyTerm) { termId.value = item?.id ?? ''; termRevision.value = item?.revision ?? 0; Object.assign(term, { kind: item?.kind ?? 'topic', key: item?.key ?? '', labels: { ru: item?.labels?.ru ?? '', de: item?.labels?.de ?? '' }, active: item?.active ?? true }); }
async function saveTerm() { if (busy.value) return; busy.value = true; error.value = ''; success.value = ''; try { await api(`/api/admin/taxonomy${termId.value ? `/${termId.value}` : ''}`,termId.value ? 'PUT' : 'POST', { ...plainCopy(term), ...(termId.value ? { expectedRevision: termRevision.value } : {}) }); editTerm(); success.value = props.messages.admin_saved; await loadTab(); } catch (problem) { error.value = adminError(problem,props.messages); } finally { busy.value = false; } }
function editTemplate(item?: CommonTemplate) { templateId.value = item?.id ?? ''; templateRevision.value = item?.revision ?? 0; block.value = item?.block ? plainCopy(item.block) : newBlock(blockType.value,['ru','de'],props.messages,media.value[0]); defaultLocale.value = item?.defaultLocale ?? 'ru'; attribution.value = item ? plainCopy(item.attribution) : emptyMetadata(); Object.assign(labels,{ ru: { ...item?.labels?.ru ?? { title: '', description: '' } }, de: { ...item?.labels?.de ?? { title: '', description: '' } } }); }
function changeBlockType() { block.value = newBlock(blockType.value,['ru','de'],props.messages,media.value[0]); }
async function saveTemplate() { if (busy.value || !block.value) return; busy.value = true; error.value = ''; success.value = ''; try { await api(`/api/admin/templates${templateId.value ? `/${templateId.value}` : ''}`, templateId.value ? 'PUT' : 'POST',{ locales: ['ru','de'], defaultLocale: defaultLocale.value, block: plainCopy(block.value), labels: plainCopy(labels), attribution: plainCopy(attribution.value), ...(templateId.value ? { expectedRevision: templateRevision.value } : {}) }); block.value = null; templateId.value = ''; success.value = props.messages.admin_saved; await loadTab(); } catch (problem) { error.value = adminError(problem,props.messages); } finally { busy.value = false; } }
onMounted(initialize);
</script>
<template><section class="admin-module admin-page"><h1>{{ messages.admin_page_title }}</h1><p>{{ messages.admin_page_intro }}</p><div v-if="error" class="admin-alert" role="alert"><p>{{ error }}</p><button type="button" :disabled="busy" @click="allowed ? loadTab() : initialize()">{{ messages.admin_retry }}</button></div><p v-if="success" class="admin-success" role="status">{{ success }}</p><p v-if="loading" role="status">{{ messages.admin_loading }}</p><template v-if="allowed"><nav class="admin-tabs" :aria-label="messages.admin_page_title"><button v-for="key in ['queue','catalog','taxonomy','templates','operations']" :key="key" :aria-current="tab === key ? 'page' : undefined" :disabled="busy" @click="changeTab(key)">{{ messages[`admin_tab_${key}`] }}</button></nav>
    <template v-if="tab === 'queue'"><label>{{ messages.admin_status_filter }}<select v-model="status" :disabled="busy" @change="loadTab"><option value="">{{ messages.admin_all }}</option><option v-for="value in ['pending','returned','approved']" :key="value" :value="value">{{ messages[`admin_status_${value}`] }}</option></select></label><p v-if="!loading && !submissions.length">{{ messages.admin_no_submissions }}</p><div class="admin-records"><article v-for="item in submissions" :key="item.id"><div class="admin-record-heading"><h3>{{ item.metadata.translations[locale]?.title || Object.values(item.metadata.translations)[0]?.title }}</h3><span class="admin-status" :class="item.status">{{ messages[`admin_status_${item.status}`] }}</span></div><p>{{ item.slug }}</p><small>{{ messages.admin_pinned_version }}: {{ item.versionId }}</small><button :disabled="busy" @click="openSubmission(item)">{{ messages.admin_review }}</button></article></div><article v-if="selected && document" class="admin-review"><h2>{{ selected.metadata.translations[previewLanguage]?.title }}</h2><p class="admin-snapshot">{{ messages.admin_pinned_version }}: {{ selected.versionId }}</p><p>{{ selected.metadata.translations[previewLanguage]?.description }}</p><div class="admin-review-controls"><label>{{ messages.admin_language }}<select v-model="previewLanguage"><option v-for="language in document.locales" :key="language" :value="language">{{ language.toUpperCase() }}</option></select></label><label>{{ messages.admin_stage }}<select v-model="stageIndex"><option v-for="(item,index) in document.stages" :key="item.id" :value="index">{{ index + 1 }}. {{ item.content[previewLanguage]?.title }}</option></select></label></div><StageRenderer v-if="projected" :stage="projected" :messages="messages" /><details v-if="stage"><summary>{{ messages.admin_private_review }}</summary><p class="plain-text">{{ stage.content[previewLanguage]?.notes }}</p><div v-for="item in stage.blocks" :key="item.id"><h4>{{ messages[item.type.replace('core.','').replaceAll('-','_')] }}</h4><p class="plain-text">{{ item.teacherNotes?.[previewLanguage] }}</p><pre v-if="item.solution">{{ JSON.stringify(item.solution, null, 2) }}</pre></div></details><p v-if="selected.reason" class="admin-return-reason">{{ selected.reason }}</p><template v-if="selected.status === 'pending'"><label>{{ messages.admin_reason }}<textarea v-model="reason" rows="3" maxlength="2000" :disabled="busy" /></label><p>{{ messages.admin_approve_hint }}</p><div class="admin-actions"><button :disabled="busy || conflict" @click="review('approve')">{{ messages.admin_approve }}</button><button class="admin-secondary" :disabled="busy || conflict || !reason.trim()" @click="review('return')">{{ messages.admin_return }}</button><button v-if="conflict" class="admin-secondary" :disabled="busy" @click="openSubmission(selected,true)">{{ messages.admin_reload_keep_reason }}</button></div></template></article></template>
    <template v-if="tab === 'catalog'"><p>{{ messages.admin_visibility_hint }}</p><p v-if="!loading && !entries.length">{{ messages.admin_no_entries }}</p><div class="admin-records"><article v-for="item in entries" :key="item.slug"><h3>{{ item.metadata.translations[locale]?.title }}</h3><p>{{ item.slug }} · {{ messages[item.status === 'approved' ? 'admin_visible' : 'admin_hidden'] }}</p><small>{{ messages.admin_pinned_version }}: {{ item.versionId }}</small><button :disabled="busy" @click="visibility('catalog',item.slug,item.revision,item.status !== 'approved')">{{ item.status === 'approved' ? messages.admin_hide : messages.admin_restore }}</button></article></div></template>
    <template v-if="tab === 'taxonomy'"><div class="admin-record-heading"><h2>{{ messages.admin_tab_taxonomy }}</h2><button :disabled="busy" @click="editTerm()">{{ messages.admin_new_term }}</button></div><form class="admin-form" @submit.prevent="saveTerm"><div class="admin-review-controls"><label>{{ messages.admin_kind }}<select v-model="term.kind" :disabled="!!termId || busy"><option v-for="kind in ['age','topic','audience','format']" :key="kind" :value="kind">{{ messages[`admin_kind_${kind}`] }}</option></select></label><label>{{ messages.admin_key }}<input v-model="term.key" required maxlength="80" pattern="[a-z0-9][a-z0-9+\-]*" :disabled="!!termId || busy" /></label></div><div class="admin-translation-grid"><label v-for="language in ['ru','de']" :key="language">{{ language.toUpperCase() }}<input v-model="term.labels[language as 'ru' | 'de']" required maxlength="200" :disabled="busy" /></label></div><label class="admin-checkbox"><input v-model="term.active" type="checkbox" :disabled="busy" />{{ messages.admin_active }}</label><button :disabled="busy">{{ messages.admin_save }}</button></form><div class="admin-records"><article v-for="item in terms" :key="item.id"><h3>{{ item.labels?.[locale] }}</h3><p>{{ messages[`admin_kind_${item.kind}`] }} · {{ item.key }} · {{ item.active ? messages.admin_active : messages.admin_inactive }}</p><button :disabled="busy" @click="editTerm(item)">{{ messages.admin_edit }}</button></article></div></template>
    <template v-if="tab === 'templates'"><div class="admin-record-heading"><h2>{{ messages.admin_common_library }}</h2><button :disabled="busy" @click="editTemplate()">{{ messages.admin_new_template }}</button></div><p>{{ messages.admin_template_hint }}</p><div class="admin-records"><article v-for="item in templates" :key="item.id"><h3>{{ item.labels?.[locale]?.title }}</h3><p>{{ item.visible ? messages.admin_visible : messages.admin_hidden }} · {{ item.versions.length }} {{ messages.admin_versions }}</p><div class="admin-actions"><button :disabled="busy" @click="editTemplate(item)">{{ messages.admin_edit }}</button><button class="admin-secondary" :disabled="busy" @click="visibility('templates',item.id,item.revision,!item.visible)">{{ item.visible ? messages.admin_hide : messages.admin_restore }}</button></div></article></div><form v-if="block" class="admin-form" @submit.prevent="saveTemplate"><div class="admin-record-heading"><h3>{{ templateId ? messages.admin_edit_template : messages.admin_new_template }}</h3><button type="button" class="admin-secondary" :disabled="busy" @click="block = null">{{ messages.admin_close }}</button></div><label v-if="!templateId">{{ messages.admin_block_type }}<select v-model="blockType" :disabled="busy" @change="changeBlockType"><option v-for="type in blockTypes" :key="type" :value="type">{{ messages[type.replace('core.','').replaceAll('-','_')] }}</option></select></label><div class="admin-translation-grid"><fieldset v-for="language in ['ru','de']" :key="language"><legend>{{ language.toUpperCase() }}</legend><label>{{ messages.admin_title }}<input v-model="labels[language as 'ru' | 'de'].title" required maxlength="200" :disabled="busy" /></label><label>{{ messages.admin_description }}<textarea v-model="labels[language as 'ru' | 'de'].description" required maxlength="200" :disabled="busy" /></label></fieldset></div><div class="admin-review-controls"><label>{{ messages.admin_language }}<select v-model="blockLanguage"><option value="ru">RU</option><option value="de">DE</option></select></label><label>{{ messages.admin_default_language }}<select v-model="defaultLocale"><option value="ru">RU</option><option value="de">DE</option></select></label></div><fieldset :disabled="busy" class="admin-block-fields"><BlockEditor :block="block" :locale="blockLanguage" :locales="['ru','de']" :media="media" :messages="messages" /></fieldset><MetadataFields v-model="attribution" :messages="messages" public-context /><button :disabled="busy">{{ busy ? messages.admin_saving : messages.admin_publish_template }}</button></form></template>
<OperationsPanel v-if="tab === 'operations'" :locale="locale" :messages="messages" /></template></section></template>
