<script setup lang="ts">
import { pointerSegment } from './editor-document';
import type { Block, Media, Messages } from './types';
import InteractiveBlockEditor from './InteractiveBlockEditor.vue';
import MediaPicker from './MediaPicker.vue';
const props = defineProps<{ block: Block; locale: string; locales: string[]; media: Media[]; messages: Messages; editorDraft?: boolean; pathBase?: string }>();
const field = (key: string) => props.pathBase ? `${props.pathBase}/content/${pointerSegment(props.locale)}/${key}` : undefined;
const emit = defineEmits<{ edited: [] }>();
function notes(event: Event) { if ((event.target as HTMLInputElement).checked) props.block.teacherNotes = Object.fromEntries(props.locales.map(locale => [locale, ''])); else delete props.block.teacherNotes; emit('edited'); }
</script>
<template>
    <template v-if="block.type === 'core.text'">
        <template v-if="block.schemaVersion === 2"><label>{{ messages.block_title }}<input v-model="block.content[locale]!.title" :data-editor-path="field('title')" /></label><label>{{ messages.presentation }}<select v-model="block.config.presentation"><option v-for="kind in ['paragraphs','list','quote']" :key="kind" :value="kind">{{ messages[kind] }}</option></select></label></template>
        <label>{{ messages.text }}<textarea v-model="block.content[locale]!.text" :data-editor-path="field('text')" rows="5" :required="!editorDraft" /></label><label v-if="block.schemaVersion === 2">{{ messages.text_source }}<input v-model="block.content[locale]!.source" :data-editor-path="field('source')" /></label>
    </template>
    <template v-else-if="block.type === 'core.presentation'"><fieldset v-if="block.content[locale]!.table"><legend>{{ messages.presentation_table }}</legend><label v-for="(header, column) in block.content[locale]!.table!.headers" :key="column">{{ messages.table_header }} {{ column + 1 }}<input v-model="block.content[locale]!.table!.headers[column]" :data-editor-path="field('table/headers/' + column)" /></label><div v-for="(row, index) in block.content[locale]!.table!.rows" :key="index" class="action-row"><label v-for="(cell, column) in row" :key="column">{{ block.content[locale]!.table!.headers[column] }} {{ index + 1 }}<input v-model="row[column]" :data-editor-path="field('table/rows/' + index + '/' + column)" /></label></div></fieldset><MediaPicker v-if="block.config.kind === 'picture-count'" :media="media" :current="block.media.image" :messages="messages" @select="block.media = { image: { assetId: $event.assetId, versionId: $event.versionId } }; $emit('edited')" /><p class="field-hint">{{ block.config.kind === 'personal-choice' ? messages.personal_choice : messages.presentation_editor_hint }}</p><label>{{ messages.text }}<textarea v-model="block.content[locale]!.text" :data-editor-path="field('text')" rows="4" :required="!editorDraft" /></label><label v-for="(mode, index) in block.content[locale]!.modes" :key="mode.modeId">{{ messages.discussion }} {{ index + 1 }}<template v-if="block.config.kind === 'picture-count'"><input v-model="mode.title" :aria-label="messages.block_title" /><input v-model="mode.label" :aria-label="messages.picture_count_mode" /><input type="number" min="0" :max="Math.min(Number(block.config.maxItems), 20)" :value="mode.count" :aria-label="messages.picture_count" @input="locales.forEach(code => { block.content[code]!.modes![index]!.count = Number(($event.target as HTMLInputElement).value) }); $emit('edited')" /></template><textarea v-model="mode.text" :data-editor-path="field('modes/' + index + '/text')" rows="2" :required="!editorDraft" /></label></template>
    <template v-else-if="block.type === 'core.image'">
        <MediaPicker :media="media" :current="block.media.image" :messages="messages" @select="block.media = { image: { assetId: $event.assetId, versionId: $event.versionId } }; $emit('edited')" />
        <p class="field-hint">{{ messages.media_notice }}</p><label>{{ messages.alt }}<input v-model="block.content[locale]!.alt" :data-editor-path="field('alt')" :required="!editorDraft" /></label><label>{{ messages.caption }}<input v-model="block.content[locale]!.caption" :data-editor-path="field('caption')" /></label><label>{{ messages.image_fit }}<select v-model="block.config.fit"><option value="contain">{{ messages.contain }}</option><option value="cover">{{ messages.cover }}</option></select></label>
    </template>
    <template v-else-if="block.type === 'core.prompt'"><label>{{ messages.text }}<textarea v-model="block.content[locale]!.text" :data-editor-path="field('text')" rows="3" :required="!editorDraft" /></label><label>{{ messages.prompt_kind }}<select v-model="block.config.kind"><option v-for="kind in ['discussion','instruction','reflection']" :key="kind" :value="kind">{{ messages[kind] }}</option></select></label><label>{{ messages.prompt_target }}<select v-model="block.config.target"><option v-for="target in ['class','pair','group']" :key="target" :value="target">{{ messages['target_'+target] }}</option></select></label></template>
    <InteractiveBlockEditor v-else :editor-draft="editorDraft" :path-base="pathBase" :block="block" :locale="locale" :locales="locales" :messages="messages" @edited="$emit('edited')" />
    <details class="block-teacher-notes"><summary>{{ messages.block_notes }}</summary><label class="checkbox-field"><input type="checkbox" :checked="!!block.teacherNotes" @change="notes" />{{ messages.add_teacher_notes }}</label><label v-if="block.teacherNotes">{{ messages.block_notes }}<textarea v-model="block.teacherNotes[locale]" :data-editor-path="pathBase ? pathBase + '/teacherNotes/' + pointerSegment(locale) : undefined" rows="3" /></label><p class="field-hint">{{ messages.private_notes_hint }}</p></details>
</template>
