<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { answerComplete, defaultAnswer, ownValue, reconcileAnswer, valueText } from './interactive';
import { appendSequenceItem, sequencePositions, shuffledItems } from './sequence-input';
import type { AnswerValue, Messages, OwnAnswer, ProjectedBlock } from './types';
const clone = (value: AnswerValue): AnswerValue => JSON.parse(JSON.stringify(value));
const props = defineProps<{ block: ProjectedBlock; messages: Messages; interactive?: boolean; answer?: OwnAnswer; disabled?: boolean; conducting?: boolean; presenter?: boolean }>();
const emit = defineEmits<{ answer: [blockId: string, value: AnswerValue]; command: [action: string, payload: Record<string, unknown>] }>();
const draft = ref<AnswerValue>(props.answer ? clone(ownValue(props.answer)) : props.block.type === 'core.sequence' ? { itemIds: [] } : defaultAnswer(props.block));
const sequencePool = ref(shuffledItems(props.block.content.items?.map(item => item.itemId) ?? []));
const dirty = ref(false);
watch(() => props.answer, incoming => { const reconciled = reconcileAnswer(draft.value, dirty.value, incoming); draft.value = reconciled.value; dirty.value = reconciled.dirty; }, { deep: true });
const locked = computed(() => props.disabled || (!props.presenter && ((!!props.block.runtime && props.block.runtime.status !== 'open') || (!!props.answer && !props.block.config.allowRepeat && !['core.roles', 'core.signals'].includes(props.block.type)))));
const results = computed(() => props.block.runtime?.results);
const presentation = computed(() => props.block.runtime?.presentation);
const revealedRoles = computed(() => props.block.content.roles?.filter(role => presentation.value?.revealedRoleIds?.includes(role.roleId)) ?? []);
function submit() { if (!locked.value && answerComplete(props.block, draft.value)) emit('answer', props.block.id, clone(draft.value)); }
function choose(optionId: string) { if (locked.value) return; if (props.presenter) { emit('command', 'choice.select', { blockId: props.block.id, optionId }); return; } draft.value = { optionId }; dirty.value = true; submit(); }
function unavailable(roleId: string) { const capacity = props.block.runtime?.availability?.find(item => item.roleId === roleId); return !!capacity && capacity.used >= capacity.capacity && ownValue(props.answer).roleId !== roleId; }
function chooseRole(roleId: string | null) { if (locked.value || (roleId && unavailable(roleId))) return; draft.value = { roleId }; dirty.value = true; submit(); }
function addSequence(itemId: string) { if (locked.value) return; if (props.presenter) { emit('command', 'sequence.select', { blockId: props.block.id, itemId }); return; } draft.value = { itemIds: appendSequenceItem(draft.value.itemIds ?? [], itemId, sequencePool.value) }; dirty.value = true; if (answerComplete(props.block, draft.value)) submit(); }
function resetSequence() { if (locked.value) return; if (props.presenter) { emit('command', 'sequence.reset', { blockId: props.block.id }); return; } draft.value = { itemIds: [] }; dirty.value = true; sequencePool.value = shuffledItems(sequencePool.value); }
function toggleSignal(key: 'ready' | 'question') { if (locked.value) return; draft.value = { ready: !!draft.value.ready, question: !!draft.value.question, [key]: !draft.value[key] }; dirty.value = true; submit(); }
const sequenceGrades = computed(() => sequencePositions(draft.value.itemIds ?? [], results.value?.itemIds));
const displayedSequence = computed(() => props.presenter ? presentation.value?.itemIds ?? [] : props.interactive ? draft.value.itemIds : presentation.value?.itemIds ?? results.value?.itemIds ?? (props.conducting ? [] : props.block.content.items?.map(item => item.itemId)));
</script>
<template>
    <form :class="['interactive-block', 'interactive-' + block.type.replace('core.', '')]" @submit.prevent="submit" @input="dirty = true" @change="dirty = true">
        <fieldset :disabled="interactive && locked"><legend>{{ block.content.question ?? block.content.text }}</legend>
            <p v-if="block.runtime" class="block-state" role="status">{{ messages['block_' + block.runtime.status] }}</p>
            <template v-if="block.content.options"><div class="choice-grid"><label v-for="(option, optionIndex) in block.content.options" :key="option.optionId" :class="['choice-option', { selected: (presenter ? presentation?.optionId : draft.optionId) === option.optionId || draft.optionIds?.includes(option.optionId), correct: results?.optionId === option.optionId || (presenter && presentation?.optionId === option.optionId && presentation?.feedback === 'correct'), incorrect: (presenter && presentation?.optionId === option.optionId && presentation?.feedback === 'incorrect') || (interactive && !!results?.optionId && draft.optionId === option.optionId && results.optionId !== option.optionId) }]">
                <input v-if="interactive && block.type === 'core.multiple-choice'" v-model="draft.optionIds" type="checkbox" :value="option.optionId" />
                <input v-else-if="interactive || (presenter && block.type === 'core.single-choice')" type="radio" :name="'answer-' + block.id" :checked="(presenter ? presentation?.optionId : draft.optionId) === option.optionId" :disabled="locked" @change="choose(option.optionId)" />
                <span class="choice-index" aria-hidden="true">{{ optionIndex + 1 }}</span><span class="choice-label">{{ option.text }}</span><strong v-if="results?.counts" class="choice-count">{{ results.counts.find(item => item.optionId === option.optionId)?.count ?? 0 }}</strong>
            </label></div><p v-if="presenter && presentation?.feedback" class="sequence-feedback" role="status">{{ messages['choice_feedback_' + presentation.feedback] }}</p><p v-if="interactive && block.type === 'core.multiple-choice'" class="field-hint">{{ messages.selection_range }} {{ block.config.minSelections }}–{{ block.config.maxSelections }}</p></template>
            <label v-if="interactive && block.type === 'core.free-response'">{{ messages.your_answer }}<textarea v-model="draft.text" required rows="4" /><small>{{ Array.from(draft.text ?? '').length }} / {{ block.config.maxLength }}</small></label>
            <template v-if="block.type === 'core.sequence'"><p v-if="interactive" class="field-hint">{{ messages.sequence_pick_hint }}</p><ol class="sequence-road" :style="{ '--sequence-columns': Math.min(5, block.content.items?.length ?? 1) }"><li v-for="(item, index) in block.content.items" :key="item.itemId" :class="['sequence-slot', sequenceGrades[index], { filled: !!displayedSequence?.[index] }]"><span class="sequence-number">{{ index + 1 }}</span><strong>{{ block.content.items?.find(candidate => candidate.itemId === displayedSequence?.[index])?.text ?? messages.sequence_empty }}</strong><small v-if="interactive && sequenceGrades[index] && sequenceGrades[index] !== 'ungraded'">{{ messages[sequenceGrades[index] === 'correct' ? 'answer_correct' : 'answer_incorrect'] }}</small><small v-if="interactive && sequenceGrades[index] === 'incorrect' && results?.itemIds?.[index]" class="sequence-expected">{{ messages.sequence_expected }}: {{ block.content.items?.find(candidate => candidate.itemId === results?.itemIds?.[index])?.text }}</small></li></ol><p v-if="presentation?.feedback" class="sequence-feedback" role="status">{{ messages['sequence_feedback_' + presentation.feedback] }}</p><div v-if="interactive || presenter" class="sequence-pool"><button v-for="identifier in sequencePool" :key="identifier" type="button" :disabled="locked || displayedSequence?.includes(identifier)" @click="addSequence(identifier)">{{ block.content.items?.find(item => item.itemId === identifier)?.text }}</button></div><div v-if="interactive || presenter" class="action-row sequence-actions"><button v-if="interactive" type="button" :disabled="locked || !draft.itemIds?.length" @click="draft.itemIds?.pop(); dirty = true">{{ messages.undo }}</button><button type="button" :disabled="locked" @click="resetSequence">{{ messages.sequence_reset }}</button></div></template>
            <template v-if="block.type === 'core.matching'"><template v-if="interactive"><label v-for="pair in draft.pairs" :key="pair.leftId">{{ block.content.left!.find(item => item.itemId === pair.leftId)?.text }}<select v-model="pair.rightId" required><option value="">{{ messages.choose_match }}</option><option v-for="item in block.content.right" :key="item.itemId" :value="item.itemId" :disabled="draft.pairs!.some(other => other.leftId !== pair.leftId && other.rightId === item.itemId)">{{ item.text }}</option></select></label></template><div v-else class="matching-columns"><ul><li v-for="item in block.content.left" :key="item.itemId">{{ item.text }}</li></ul><ul><li v-for="item in block.content.right" :key="item.itemId">{{ item.text }}</li></ul></div></template>
            <template v-if="block.type === 'core.roles' && conducting && !interactive"><div class="role-reveal-board"><p class="role-current">{{ revealedRoles.at(-1)?.text ?? messages.role_first_hint }}</p><div class="revealed-role-list"><span v-for="role in revealedRoles" :key="role.roleId">{{ role.text }}</span></div><div v-if="presenter" class="action-row"><button type="button" class="primary" :disabled="locked || revealedRoles.length >= (block.content.roles?.length ?? 0)" @click="$emit('command', 'role.reveal.next', { blockId: block.id })">{{ messages.role_next }}</button><button type="button" :disabled="locked || !revealedRoles.length" @click="$emit('command', 'role.reveal.reset', { blockId: block.id })">{{ messages.sequence_reset }}</button></div></div></template><template v-else-if="block.type === 'core.roles'"><div class="role-grid"><button v-for="role in block.content.roles" :key="role.roleId" type="button" :class="['role-card', { 'role-card-selected': draft.roleId === role.roleId, 'role-card-taken': unavailable(role.roleId) }]" :disabled="!interactive || locked || unavailable(role.roleId)" :aria-pressed="interactive ? draft.roleId === role.roleId : undefined" @click="chooseRole(role.roleId)"><strong>{{ role.text }}</strong><span v-if="block.runtime?.availability" class="role-capacity">{{ block.runtime.availability.find(item => item.roleId === role.roleId)?.used }} / {{ block.runtime.availability.find(item => item.roleId === role.roleId)?.capacity }}</span><small>{{ draft.roleId === role.roleId ? messages.role_selected : unavailable(role.roleId) ? messages.role_taken : messages.role_available }}</small></button></div><button v-if="interactive" type="button" class="role-release" :disabled="locked || !draft.roleId" @click="chooseRole(null)">{{ messages.no_role }}</button></template>
            <template v-if="interactive && block.type === 'core.signals'"><div class="signal-buttons"><button type="button" :class="{ selected: draft.ready }" :aria-pressed="!!draft.ready" :disabled="locked || (!!draft.question && !answer?.acknowledged)" @click="toggleSignal('ready')">{{ messages.ready }}</button><button type="button" :class="{ selected: draft.question }" :aria-pressed="!!draft.question" :disabled="locked" @click="toggleSignal('question')">{{ messages.question_signal }}</button></div><p v-if="answer?.acknowledged" role="status">{{ messages.question_acknowledged }}</p></template>
            <button v-if="interactive && (!['core.single-choice', 'core.poll', 'core.roles', 'core.sequence', 'core.signals'].includes(block.type) || (block.type === 'core.sequence' && dirty && answerComplete(block, draft)))" class="primary" :disabled="locked || !answerComplete(block, draft)">{{ messages.submit_answer }}</button>
        </fieldset>
        <p v-if="answer" class="answer-confirmed" role="status">{{ messages.answer_saved }}<span v-if="answer.status !== 'submitted'"> · {{ messages['moderation_' + answer.status] }}</span><span v-if="answer.grade !== null"> · {{ messages[answer.grade ? 'answer_correct' : 'answer_incorrect'] }}</span></p>
        <p v-if="interactive && block.type === 'core.sequence' && results?.itemIds" role="status">{{ sequenceGrades.filter(grade => grade === 'correct').length }} / {{ block.content.items?.length }}</p><p v-if="interactive && answer?.privateReply" class="private-reply" role="status"><strong>{{ messages.teacher_reply }}</strong> {{ answer.privateReply }}</p><div v-if="results" class="block-results"><h3>{{ messages.results }}</h3><p v-if="results.totalAnswers !== undefined">{{ messages.answers_received }}: {{ results.totalAnswers }}</p><p v-if="results.optionId || results.optionIds || results.itemIds || results.pairs" class="plain-text">{{ messages.revealed_answers }}: {{ valueText(block.content, results, messages) }}</p><blockquote v-for="(entry, index) in results.published" :key="index" class="plain-text">{{ entry.text }}</blockquote></div>
    </form>
</template>
