<script setup lang="ts">
import { reactive, watch } from 'vue';
import { valueText, responseTextValid } from './interactive';
import { initialModeration, moderationPayload, reconcileModeration, type ModerationDraft } from './moderation';
import type { Messages, ProjectedStage, TeacherAnswer, TeacherState } from './types';
const props = defineProps<{ session: TeacherState; stage: ProjectedStage; answers: TeacherAnswer[]; messages: Messages; disabled: boolean }>();
const emit = defineEmits<{ command: [action: string, payload: Record<string, unknown>] }>();
const drafts = reactive<Record<number, ModerationDraft>>({});
watch(() => props.answers, answers => { for (const answer of answers) if (answer.moderation) drafts[answer.id] = drafts[answer.id] ? reconcileModeration(drafts[answer.id]!, answer) : initialModeration(answer); }, { immediate: true, deep: true });
const maxLength = (blockId: string) => props.stage.blocks.find(block => block.id === blockId)?.config.maxLength ?? 500;
function text(answer: TeacherAnswer) { const block = props.stage.blocks.find(block => block.id === answer.blockId); return block ? valueText(block.content, answer.value, props.messages) : ''; }
</script>
<template>
    <section id="conducting-answers" class="studio-card participants" tabindex="-1"><div class="section-heading"><h2>{{ messages.student_answers }}</h2><span class="answer-total">{{ messages.answers_received }}: {{ answers.length }}</span></div><p class="field-hint">{{ messages.activity_hint }}</p><p v-if="!session.participants.length" class="field-hint">{{ messages.waiting_participants }}</p>
        <div v-for="participant in session.participants" :key="participant.id" class="participant"><span class="participant-initial" aria-hidden="true">{{ Array.from(participant.name.trim())[0]?.toLocaleUpperCase() }}</span><div class="participant-content"><div class="participant-name"><strong>{{ participant.name }}</strong><span class="participant-activity">{{ participant.connected ? messages.participant_connected : messages.participant_away }}</span></div><small v-if="!answers.some(answer => answer.participantId === participant.id)">{{ messages.no_answers }}</small>
            <div v-for="answer in answers.filter(answer => answer.participantId === participant.id)" :key="answer.id" class="teacher-answer"><small>{{ stage.blocks.find(block => block.id === answer.blockId)?.content.question ?? stage.blocks.find(block => block.id === answer.blockId)?.content.text }}</small><p class="plain-text"><strong v-if="answer.moderation">{{ messages.original_answer }}: </strong>{{ text(answer) }}</p><p v-if="answer.grade !== null">{{ messages[answer.grade ? 'answer_correct' : 'answer_incorrect'] }}</p>
                <div v-if="answer.moderation && drafts[answer.id]" class="moderation-form"><p class="field-hint">{{ messages['moderation_' + answer.moderation.status] }} · {{ messages[answer.moderation.published ? 'answer_published' : 'answer_unpublished'] }}</p><label>{{ messages.display_answer }}<textarea v-model="drafts[answer.id]!.text" rows="3" :disabled="disabled" @input="drafts[answer.id]!.dirty = true" /><small>{{ Array.from(drafts[answer.id]!.text).length }} / {{ maxLength(answer.blockId) }}</small></label><p class="field-hint">{{ messages.moderation_hint }}</p><p v-if="drafts[answer.id]!.revision !== answer.revision" class="info-banner" role="status">{{ messages.answer_changed }} <button :disabled="disabled" @click="drafts[answer.id] = { text: drafts[answer.id]!.text, revision: answer.revision, dirty: true }">{{ messages.use_current_revision }}</button><button :disabled="disabled" @click="drafts[answer.id] = initialModeration(answer)">{{ messages.reload_answer }}</button></p><div class="action-row"><button :disabled="disabled || !responseTextValid(drafts[answer.id]!.text, maxLength(answer.blockId))" @click="$emit('command', 'answer.moderate', moderationPayload(answer.id, drafts[answer.id]!, 'approved'))">{{ messages.approve_answer }}</button><button :disabled="disabled" @click="$emit('command', 'answer.moderate', moderationPayload(answer.id, drafts[answer.id]!, 'rejected'))">{{ messages.reject_answer }}</button><button v-if="!answer.moderation.published" :disabled="disabled || answer.moderation.status !== 'approved' || drafts[answer.id]!.dirty" @click="$emit('command', 'answer.publish', { answerId: answer.id, expectedAnswerRevision: answer.revision })">{{ messages.publish_answer }}</button><button v-else :disabled="disabled" @click="$emit('command', 'answer.unpublish', { answerId: answer.id, expectedAnswerRevision: answer.revision })">{{ messages.unpublish_answer }}</button></div></div>
            </div>
        </div></div>
    </section>
</template>
